rplugin/python3/plugin.py
- Set filetype to markdown and text wrapping.
- This change improves the user experience: we provide a more organized and readable chat environment
=> feat: add configuration options for wrap and filetype

rplugin/python3/plugin.py
This PR uses `buf_set_lines` & `buf_set_text` methods to append new tokens to the end of the chat buffer, no matter which window is active and no matter the user's current cursor position.
This makes moving the cursor / changing window mid generation possible without new tokens spewing out at the current cursor position.
=> Use `buf_set_lines` & `buf_set_text` methods instead of `nvim.current.line`

CHANGELOG.md, README.md, lua/CopilotChat/init.lua, rplugin/python3/copilot.py, rplugin/python3/handlers/chat_handler.py
=> feat: Proxy support

lua/CopilotChat/health.lua
Hi, I want neovim to use an isolated python environment and specified the executable via `g:python3_host_prog` variable. 
I think it's legit to expect CopilotChat.nvim plugin to run on it also. Could you accept this patch?
=> Use g:python3_host_prog

lua/CopilotChat/init.lua
Fixed a minor typo. The typo didn't break anything.
=> fix: fixed a typo in the prompt

README.md, lua/CopilotChat/init.lua, rplugin/python3/CopilotChat/handlers/chat_handler.py, rplugin/python3/CopilotChat/handlers/inplace_chat_handler.py, rplugin/python3/CopilotChat/handlers/vsplit_chat_handler.py, rplugin/python3/CopilotChat/prompts.py
Hi! I added the ability to set the language of Copilot answers.
If you originally create a prompt in the language you want the answer to be in "opts.prompts", the answer will be created in the corresponding language.
However, it is difficult to configure with "CopilotChatFixDiagnostic", so I added this setting item.
It works by adding language to opts in the settings.
If nothing is set, you will receive answers in English as before.
```
opts = {
show_help = "yes",         -- Show help text for CopilotChatInPlace, default: yes
debug = false,             -- Enable or disable debug mode, the log file will be in ~/.local/state/nvim/CopilotChat.nvim.log
disable_extra_info = 'no', -- Disable extra information (e.g: system prompt) in the response.
language = 'Japanese',
}
```
If it is not …
=> Language settings for copilot answers

rplugin/python3/CopilotChat/handlers/chat_handler.py
This was causing an error on a fresh install.
100% understand if rather have a different fix!
Thanks for an awesome plugin.
=> fix: add check for temperature if empty string

README.md, rplugin/python3/CopilotChat/copilot.py, rplugin/python3/CopilotChat/copilot_plugin.py
Small addition of `:CopilotChatBuffer` that will pull in the current in-focus buffer and utilize it for answering the question. 
Also included small bug fixes that technically might never be encountered
[ChatBuffer.webm](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/3443378/686d1b09-aa1c-434c-b4c1-e4a528ac1875)
=> New Command so that CopilotChat reads from current in-focus buffer when answering questions

README.md
Hi, 
I don't know if this the correct way to use this, but when i tried it made more sense to have a space after these commands for input.
calling CopilotChatBuffer with no args throw
```
E471: Argument Required
```
=> docs: input for items with args

README.md
I accidently made a PR with broken code for CopilotChatBuffer thanks @MikaelElkiaer for pointing that out
refer to this https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/79#discussion_r1505437986
=> docs: fixed up incorrect syntax for CopilotChatBuffer

lua/CopilotChat/chat.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/select.lua
- Do not send config that is merged with global config to M.open in M.ask so M.open do not thinks we are sendign layout change
- Properly mark chat as started from on_start event so the check for word at start of new copilot chat always works
- Add support for Visual Block selection to select.visual and optimize the existing code for other visual modes
- Fix issue where select.visual would enter insert mode instead of just exiting visual mode to normal mode
- Add support for getting cached copilot token on windows and error handling
=> Fix some inconsistencies with Lua refactor

lua/CopilotChat/init.lua
This for example allows window right below cursor in style of vscode inline popup.
Example:
```lua
chat.setup({
window = {
layout = 'float',
relative = 'cursor',
width = 1,
height = 0.4,
row = 1
}
})
```
=> Add support for more layout options for chat window

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/select.lua
- Visual selection now uses also '< and '> as fallback when in command line mode
- Remove vim.print that I forgot when setting folds
- Add set_debug function that updates M.config.debug and updates logger
- Properly update prompts in case reference in prompt references another reference
=> Fix issues with visual selection and folds, add set_debug

lua/CopilotChat/init.lua, lua/CopilotChat/select.lua
This commit introduces the ability to select git diff content and generate commit messages following the commitizen convention. It adds two new selection methods, `Commit` and `CommitStaged`, to the `CopilotChat` module. These methods return the current git diff, with `CommitStaged` specifically returning staged changes. The `gitdiff` function in the `select` module is also updated to support this feature. This enhancement improves the utility of the chatbot in a version control context.
**This message was generated by this change :d**
=> feat: add git diff selection and commit message generation

lua/CopilotChat/init.lua, lua/CopilotChat/select.lua
- Update selection with <Esc> on window opening not after
- Store last used config to be used in mappings
=> fix: Use proper config for selection and update selection earlier

.editorconfig, README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/debuginfo.lua, lua/CopilotChat/init.lua, lua/CopilotChat/prompts.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/utils.lua
Closes #5 
How it works:
1. Grabs outline for all functions for all currently opened buffers
2. Generates embeddings for all the functions
3. Generates embedding from current code selection
4. Uses spatial cosine distance to find similar embeddings to code selection
5. Sends top x matched embeddings as part of the query to copilot in format:
````markdown
query
File: `<filename1>`
```<filetype_for_filename1>
<embeddings_for_filename1>
```
File: `<filename2>`
```<filetype_for_filename2>
<embeddings_for_filename2>
```
etc
````
TODO:
=> feat: Add support for embeddings

lua/CopilotChat/chat.lua
When migrating to the canary branch, making most of the migration changes, and using the same, but slightly modified, config by [@jellydn](https://github.com/jellydn/lazy-nvim-ide/blob/main/lua/plugins/extras/copilot-chat-v2.lua). 
I then highlighting a selection, using `<leader>ccp`, and then asking for a review, the following error appears.
```
Error: E5108: Error executing lua: ...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/chat.lua:118: attempt to concatenate local 'self' (a table value)
stack traceback:
...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/chat.lua:118: in function 'open'
...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/init.lua:263: in function 'open'
...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/init.lua:292: in function 'ask' …
```
=> fix: Typo in chat.lua

lua/CopilotChat/context.lua
- Just silently do not produce outline when TS parser is missing
- Handle TS aliases like vim.treesitter.language.register('bash', 'zsh')
=> fix: Handle missing TS parsers gracefully, handle TS aliases

lua/CopilotChat/health.lua
- Also add check for stable >=0.9.5
=> feat: Improve healthcheck messages with fix instructions

lua/CopilotChat/prompts.lua
Useful for showing provided context when chaining prompts
=> feat: Add SHOW_CONTEXT prompt

lua/CopilotChat/chat.lua
Its possible that spinner is not set yet when opening new window with custom layout
=> fix; Null check spinner when closing chat

lua/CopilotChat/copilot.lua
This ensures that huge requests are passed in correctly without possible mistakes when executing the shell
=> fix: Use temp files when making curl requests

lua/CopilotChat/copilot.lua, lua/CopilotChat/utils.lua
Use lua ones, they are better and not blocked on non-vim loop.
Closes #181 
Closes #183
=> fix: Avoid using vim functions for managing temp files

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/spinner.lua
Without this when entering new prompt while one is already running, the chat do not properly outputs the change. Also this makes sure that job is cancelled early so on_done, on_error callbacks after are skipped to reduce text being written to buffer when not necessary/wanted.
=> fix: Improve stability of job cancellation and chat reset

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua
Needs to be set when showing the text and not in advance. Accidentally broke this in a72ad269de9621a3df31afab281674b54ce3320b
=> fix: Fix diff highlights for overlays

README.md, lua/CopilotChat/chat.lua
Updates README.md with buffer names and autocommand to set local options for these buffers. Also removes overriding users relative number setting.
Referenced in this discussion: #196 
In **README.md** > **Configuration**:
You can set local options for the buffers that are created by this plugin: `copilot-diff`, `copilot-system-prompt`, `copilot-user-selection`, `copilot-chat`.
```lua
vim.api.nvim_create_autocmd('BufEnter', {
pattern = 'copilot-*',
callback = function()
vim.opt_local.relativenumber = true
end
})
```
=> docs: explain setting buffer options and remove default for relative number

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua
No reason to write out the tokens to buffer,and it also messes up the history when saving chats so just show it as virtual line instead
=> feat: Show token count as virtual line instead of in buffer

lua/CopilotChat/actions.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/integrations/fzflua.lua, lua/CopilotChat/integrations/telescope.lua
Instead of definining the selection when generating actions and hardcoding it, use prompt configuration for grabbing selection.
Closes #206
=> fix: Use prompt selection when picking prompts

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/prompts.lua
=> feat: Add start and end line number as line range to active selection

.github/workflows/ci.yml, lua/CopilotChat/init.lua
This also fixes issue with panvimdoc generating CopilotChat-copilot-chat-for-neovim- as prefix for everything, now its just CopilotChat-
=> fix: Warn users about configuration cchange and do not break plugin

doc/CopilotChat.txt, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Closes #218
The callback function in both the 'ask' and 'config' methods now receives the 'source' parameter. This allows users to access information about the source of the response, such as the buffer number and window number. This change enhances the flexibility and usability of the callback function.
=> feat: Add source parameter to callback function

lua/CopilotChat/chat.lua, lua/CopilotChat/overlay.lua
This improves support for various integrations like nvim-cmp and edgy
Closes #228
=> feat: Set chat and overlay filetypes to their names

lua/CopilotChat/config.lua
C-m is same as CR on a lot of terminals, remap to C-s
Closes #246
=> fix: Remap bindings to not conflict with terminal

lua/CopilotChat/integrations/telescope.lua
If the prompt contains newlines, the error
`'replacement string' item contains newlines` will occur when previewing the Telescope integration. This is because `nvim_buf_set_lines` prohibits newlines from being included in the content it sets. Instead, this function takes a list of strings as arguments.
In this commit, vim.split splits strings with newlines. With this fix, Telescope preview will work correctly even when the prompt contains newlines.
=> Fix telescope preview if prompt contains newlines

README.md
For chat headers, config.lua was updated before but README wasnt
=> docs: Match README config with config.lua

lua/CopilotChat/copilot.lua
Copilot api can return error off-topic for example, when you try something like this:
`Why weren't I invited when my parents got married?`
=> fix: Handle error responses from copilot properly

lua/CopilotChat/copilot.lua
The copilot module now first tries to load the GitHub token from the environment variable 'GITHUB_TOKEN'. If the variable is not set, it falls back to loading the token from the file.
=> feat(copilot): load GitHub token from environment

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/prompts.lua
- Normalize different generation system prompts into one COPILOT_GENERATE
- Add COPILOT_REVIEW system prompt and CopilotChatReview that auto adds diagnostics based on response
- Use current VS Code prompts for generation of docs, tests and explanation
Example of Review command (adapted from #214 by @aweis89):
=> feat: Normalize generation prompts, add Review prompt, use more vscode prompts

lua/CopilotChat/init.lua
This fixes a bug where the mode remains in insert mode after closing the chat window.
=> fix: send stopinsert command on close

README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua
Instead of opening horizontal/vertical split this new option replaces current buffer with chat buffer in current window
=> feat: Add 'replace' layout that replaces current buffer in window

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua
=> fix: Properly replace state when calling setup() second time

lua/CopilotChat/select.lua
Useful for providing system clipboard contents easily (for example for using CopilotChat quickly in replace mode in tmux popup etc)
=> feat: Add support for select.clipboard

lua/CopilotChat/health.lua
closes #321 
Let's consider 0.10 as stable version from now on. I suppose 0.9.5 still can be considered as stable for a few months until majority of people will migrate to 0.10
=> fix: consider 0.10 as stable and 0.11 as nightly

lua/CopilotChat/copilot.lua
In apps.json it looks like app id can be prepended to github.com key, so just grab first match instead.
=> fix: Find github.com in hosts/apps.json instead of getting it directly

lua/CopilotChat/chat.lua
This prevents someone replacing buffer in copilot chat window with other buffer and chat not being able to recover
=> fix: check if buffer is in chat window to validate chat being visible

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
I added a new option `highlight_selection`, that highlights the selection in the source buffer when in the chat window.
The highlight is only visible when the chat window is focused.
The hl group for the selection is `CopilotChatSelection` and is linked to `Visual` by default.
The option is enabled by default.
Let me know what you think!
=> feat: highlight the selection in the source buffer

lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
As discussed, the separator is now repeated in a virtual line and has hl group `CopilotChatSeparator`.
The headers have `hl_group` `CopilotChatHeader`.
I didn't change the default header strings, so they still have `##`, but that's no longer needed to get the same styling.
 
With custom header strings:
Closes #334
=> feat: enhanced header rendering in the chat window

README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua, lua/CopilotChat/spinner.lua, lua/CopilotChat/utils.lua
- As pointed out in recent PRs with highlight changes, create_namespace do not rly needs to be stored so we do not need to pass them around everywhere. This simplifies the code a bit
- To make the highlights consistent after recent highlight changes, make the remaining highlights configurable as well
=> chore: Pass namespaces around less, make help and spinner highlight configurable

lua/CopilotChat/init.lua
Selection returns empty table in case there is no selection so check for fields being set instead like on other places.
=> fix: Properly check if selection is unset when highlighting

lua/CopilotChat/chat.lua
Currently the fold is pretty much never reset to 0 so if you use fold levels for determining if there is fold or not you cant tell. Vim somehow can by default but any custom logic (for example custom statuscolumn) cant.
=> fix: Fix fold levels

README.md, lua/CopilotChat/integrations/cmp.lua
=> feat: Add nvim-cmp integration

lua/CopilotChat/integrations/cmp.lua
Need to reset copilot-chat buffer to unlisted after accepting any nvim-cmp item as nvim-cmp for some reason sets the buffer as listed internally.
See discussion here: https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/345#issuecomment-2140483687
=> fix(cmp): unlist copilot-chat buffer after cmp item acceptance

lua/CopilotChat/init.lua
Hi! 
This MR fixes this bug:
When user types `/Fi` in chat and then presses `<TAB>`
Expected: only `Fix` and `FixDiagnostic` are shown
Result: all actions are shown
Reference: https://neovim.io/doc/user/pattern.html#search-pattern
=> fix: Improve regexp for command completion in chat

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua
Potentially debatable: automatically rewrite `gpt-4o` to `gpt-4o-2024-05-13` because the server doesn't do that for us despite allowing the short name for `gpt-4` and `gpt-4-turbo`.
=> Use gpt-4o by default

lua/CopilotChat/integrations/cmp.lua
Previously, completion in nvim-cmp would only happen when typing the `@` or `/` character. There
was no way to type a partial command (e.g. `/COPILOT_G`) and then autocomplete.
This PR adds a keyword pattern to allow this sort of completion in a case-insensitive way.
If the previous behavior was an intentional design decision, feel free to close this PR. (I changed
it for my own usage, but figured other people might like it as well.)
=> Improve completion of Copilot keywords

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
The following PR adds a config option to override the default `yank_diff` register. Currently, the default is set to `"`, and it can conflict with configuration settings that set the system clipboard to the unnamed register. This override enables me to set the `yank_diff_register` to the `+` register and maintain my current system clipboard setting of `vim.o.clipboard = 'unnamedplus'`
The default would remain the same, but it would allow this to be changed as needed.
This could address issue #364
=> Add support for overriding the default yank_diff register

lua/CopilotChat/select.lua
This fixes issue with switching directories after opening neovim.
Closes #387
=> Use cwd for selection.gitdiff

lua/CopilotChat/select.lua
getcwd is not reliable and straight up doesnt work even when supplying correct window number as first parameter so use filename instead
Closes #387
=> Properly resolve directory based on source buffer name

lua/CopilotChat/copilot.lua
Also use $HOME instead of ~ as its more friendly for expansion on different OS.
Fixes #409
=> fix: Use $LOCALAPPDATA when loading github token

lua/CopilotChat/init.lua
Fix issue that running `:CopilotChatLoad <name>?` without opening any panel before will result in error of indexing nil `config`.
=> Fix indexing nil `config`

lua/CopilotChat/select.lua
This happens when running diff from `git commit` message.
Closes #417
=> Do not run git diff against .git directory

lua/CopilotChat/actions.lua, lua/CopilotChat/select.lua
Replaced `vim.lsp.diagnostic.get_line_diagnostics` with `vim.diagnostic.get` to align with the updated Neovim API.
```
- WARNING vim.lsp.diagnostic.get_line_diagnostics is deprecated. Feature will be removed in Nvim 0.12
- ADVICE:
- use vim.diagnostic.get instead.
- stack traceback:
/Users/radwo/.local/share/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/actions.lua:17
/Users/radwo/.config/nvim/lua/radwo/plugins/copilot.lua:20
```
=> refactor: migrate deprecated get_line_diagnostics to vim.diagnostic.get

lua/CopilotChat/tiktoken.lua
implemented suggestion from #418 
Closes #418
=> fix: tiktoken download fail if cache folder doesn't exist

Makefile
Also, add curl flags for correct script-friendly error handling. Without these, one ends up with tiktoken_core.so containing "Not Found".
=> fix: Download tiktoken binaries from correct location

lua/CopilotChat/utils.lua
Feedkeys can sometimes cause very annoying delays especially when opening fresh chat window, this solves that
=> Use vim.cmd instead of feed keys for exiting visual mode

lua/CopilotChat/actions.lua, lua/CopilotChat/integrations/fzflua.lua
The help_actions prompts end with a double quote, and passing that to
shell unescaped explodes with
sh: 1: Syntax error: Unterminated quoted string
We could escape it using fzf-lua.libuv.shellescape, but it's easier to
just let fzf-lua do the right thing itself:
https://github.com/ibhagwan/fzf-lua/blob/052491ee887b04e231787515a81aa3f358a68147/lua/fzf-lua/core.lua#L645-L646
There's no point having a quote at the end of the prompt if it's never
getting closed (and it isn't indeed). Also, the prompt used for
CopilotChatFixDiagnostic doesn't have any quotes either, so to be
consistent let's just remove them from actions prompts as well.
=> fix: "Unterminated quoted string" in fzflua; extra quotes in actions prompts

README.md, lua/CopilotChat/actions.lua, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/select.lua, lua/CopilotChat/utils.lua
- Automatically include diagnostics in selections. This means that the chat will always know about them as well
- With diagnostics automatically included, CopilotChatFixDiagnostics is no longer necessary, CopilotChatFix is enough
- With diagnostics automatically included, actions.help_actions also no longer serves any purpose, CopilotChatExplain + CopilotChatFix is enough
- To better incorporate new workflow, also default to visual || buffer for selection (which was popular config adjustment in first place anyway)
=> Revamp how diagnostics are handled

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/integrations/cmp.lua
https://docs.github.com/en/copilot/building-copilot-extensions/about-building-copilot-extensions
- Change @buffer and @buffers to #buffer and #buffers
- Add support for @agent agent selection
- Add support for config.agent for specifying default agent
- Add :CopilotChatAgents for listing agents (and showing selected agent)
- Remove :CopilotChatModel, instead show which model is selected in :CopilotChatModels
- Remove early errors from curl so we can actually get response body for the error
- Add info to README about models, agents and contexts
Closes #466
=> Add support for copilot extension agents

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/prompts.lua
- Use new VSCode format for embedding files
- Use new VSCode format for active selection
- Use new VSCode explain and generic prompts
- Remove workspace prompt, we dont have workspace support so for now no need for it rly and it can easily become outdated too
=> Adjust how messages are built to match new vscode requests

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/debuginfo.lua, lua/CopilotChat/health.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Support workspace file map context. This context will simply include all related filenames to the prompt in chat context. Useful for searching where something might be (but limited to only searching on filenames for now).
=> Add support for #files (workspace file map) context

lua/CopilotChat/init.lua
Add arrow (>) at the end of prompts in model and agent selection menus to better indicate that user input is expected.
=> style: improve model/agent selection prompts

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua
Auto follow cursor is generally a convenient and desirable feature. However, it gets annoying when the model is streaming a very long response spanning more vertical space than the chat window has. In such cases the user might want to read the response from the beginning at a human pace, yet auto follow keeps pushing forward at robot speed.
This PR improves auto follow cursor behavior by conditioning it on the current cursor position. If it is at the last line, auto-following happens. Otherwise, the cursor stays where it is. Effectively, this means that the user can prevent auto-following from happening by simply moving the cursor up.
=> feat(chat): improve auto follow cursor behavior

lua/CopilotChat/chat.lua
These fields are not meant to be used from outside so dont expose them.
=> Remove private fields from chat class type definition

README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua
Good with plugins like render-markdown.nvim
=> Add option to disable header highlighting

README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/prompts.lua
- Everything in blockquote is copied to the next prompt and added at start
automatically. This is useful for preserving context/agents etc.
- Remove SHOW_CONTEXT prompt as with sticky its no longer necessary imo and
claude works fine without additional debugging.
- Use new sticky feature with default prompts so the system prompt choice is
remembered automatically
- Add new `toggle_sticky` mapping for toggling sticky line under cursor
- Update README with sticky prompts, prompts and system prompts
Example:
```markdown
> #files
explain me this
---
> #files
```
=> Add support for sticky prompt section with `> `

lua/CopilotChat/init.lua
- Instead of passing state.source around, simply update it only if we are outside of chat window and make M.open() noop otherwise
- Unify when last prompt is cleared, clear it in .ask always instead of doing it only when explicitely submitting prompt
=> Simplify how source buffer is being saved and unify prompt clearing

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/debuginfo.lua, lua/CopilotChat/init.lua, lua/CopilotChat/select.lua
Now contexts are defined in configuration with input and resolve functions. This allows for more flexible and extensible context system. It also makes the system more robust and easier to understand.
The changes include:
- Add context inputs (with `:` after context) for additional parameters
- Add proper model selection (with `$` prefix)
- Move context resolution logic to config.lua
- Extract git diff to context.gitdiff
- Simplify outline/files logic, make it more modular
- Improve pattern matching for context/model/agent parsing
- Add truncation for large selections
=> feat(context): rewrite context system with input and resolving

lua/CopilotChat/init.lua
Add missing help line for model selection using `$<model>` syntax in the chat help overview.
=> docs: add missing help for model selection

lua/CopilotChat/init.lua
Accidentally forgot to load it after reworking how contexts work
=> Fix loading of default context

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua
This means it can be properly overriden when opening chat and also follows same loading as other chat configuration already does
=> Load chat auto_insert from config instead of passing it in contructor

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/integrations/cmp.lua, lua/CopilotChat/utils.lua
Adds new config option `chat_autocomplete` (enabled by default) that will trigger completion automatically when typing trigger characters (@, /, #, $, :). This replaces the nvim-cmp integration which is now deprecated in favor of this new solution.
The automatic completion is debounced to avoid too many triggers and uses the same completion logic as before, just moved to separate function.
=> feat: add automatic chat autocompletion

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
Previously the semantic embeddings were using older model and not using the query in most optimal way. Now it is using text-embedding-3-small model for reduced cost and better performance, embeddings are stored in 512 dimensions and the embedding process was refactored to be more straightforward and use less API calls by including the query in the initial embedding call.
Also slightly improves the formatting of the embedding prompt to be more readable.
=> refactor: improve semantic embeddings performance

README.md, lua/CopilotChat/init.lua
Previously, the documentation for custom prompts, system prompts and contexts was scattered and duplicated across multiple sections. This change consolidates and improves the documentation by:
- Moving examples next to their relevant sections
- Adding clearer and more concise examples for custom prompts, system prompts and contexts
- Removing duplicate content that was spread across multiple sections
- Making github/copilot.vim the primary recommended Copilot backend
=> docs: improve README with better examples and cleaner structure

lua/CopilotChat/config.lua, lua/CopilotChat/context.lua
=> Use relative paths for file references in contexts

README.md, lua/CopilotChat/init.lua
Instead of creating new error section, show error inline in response to not waste chat space
=> Show errors inline in response

lua/CopilotChat/chat.lua, lua/CopilotChat/diff.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua, lua/CopilotChat/prompts.lua, lua/CopilotChat/utils.lua
Extract diff handling into separate class to reduce code duplication and improve maintainability. Add custom highlighting namespace in diff class and remove redundant code from overlay class. Add utility function for finding lines between patterns. Improve diff accepting/showing logic with proper line number handling.
Move highlighting setup into dedicated diff class and make overlay class more focused. Add example for code snippet markdown links in prompts to improve clarity.
=> refactor: improve diff handling implementation

lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/debuginfo.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Rather than using harsh big file threshold for converting files/buffers
to outline format, outline is now used mostly for similarity scoring.
This preserves the original content while improving the accuracy of
content matching.
Additionally:
- Move find_config_path to utils module for reuse
- Add buffer function to get full buffer content
- Rewrite outline function to work with strings rather than buffers
Signed-off-by: Tomas Slusny <slusnucky@gmail.com>
=> refactor(context): improve accuracy of buffer processing

README.md
=> docs: Use content instead of lines in custom selector example

lua/CopilotChat/chat.lua
This prevents UI issue where chat is outputting but spinner is not spinning until new text is appended. Spinner can spin in background just fine so let it.
=> Do not stop spinner on closing window

lua/CopilotChat/init.lua
Ensures completion menu is only shown when user is in insert mode to prevent unexpected behavior when triggering completion in other modes.
=> fix: check if in insert mode before showing completions

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/prompts.lua, lua/CopilotChat/select.lua
This change implements better handling of large files by adding truncation logic for both files and their outlines. The main improvements include:
- Add truncation for files over 2000 lines
- Add truncation for outlines over 600 lines
- Use relative paths for filenames for better context display
- Improve context formatting with proper file links
- Add default values for unknown filenames and filetypes
These changes help prevent token limits being exceeded while still preserving important context for the LLM.
=> feat: truncate large files and improve context output

lua/CopilotChat/init.lua
Add fallback pattern matching for file headers without markdown link format. This ensures the plugin works correctly with both markdown and plain text file references in the header.
=> fix: make header pattern matching more robust

lua/CopilotChat/init.lua
The '%' character in the pattern matching string doesn't need to be escaped as it's not a special pattern matching character in Lua.
=> fix: remove unnecessary escape in pattern matching

lua/CopilotChat/init.lua
- Use header info (filename/lines) if no selection is available
- Compare header info with current buffer name to validate that the diff can be applied
=> feat: support header diff matching without selection

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/diff.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Adds new mapping that allows jumping to the target file and line number from the diff view. If the target file is already open in a buffer, it will switch to that buffer. Otherwise, it creates a new buffer with proper filetype.
This improves navigation between diff view and source files, making it easier to review and apply suggested changes.
=> feat: add jump to diff feature with `gj` mapping

lua/CopilotChat/init.lua
Sometimes the content might not exist (when generating new files) and this can throw error.
=> fix: Set jump marks safely after diff jumping

lua/CopilotChat/init.lua
Without this its hard to see the help text at the end
=> chore: add extra newline when showing system prompt and selection

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Add new mapping 'gq' that populates quickfix list with code blocks from AI responses. Each entry includes source file and line numbers if available, making it easier to navigate through suggested code changes.
Also fixes selection update to ignore special window types.
=> feat: add quickfix list for code blocks in chat

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
Add new configuration option for suppressing output and chat history storage.
This enables using CopilotChat purely as a backend service by handling
responses through callbacks without any UI interaction or state persistence.
See #551
=> feat(chat): add no_chat option

lua/CopilotChat/chat.lua
The treesitter parser initialization for markdown was redundant since the buffer's syntax is already set to markdown via vim.bo[bufnr].syntax.
=> refactor: remove redundant treesitter parser init

lua/CopilotChat/copilot.lua, lua/CopilotChat/diff.lua, lua/CopilotChat/utils.lua
Moves uuid, machine_id and quick_hash functions from copilot.lua to utils.lua module. Also improves type annotations and documentation for the moved functions. Removes unused table_equals function and renames blend_color_with_neovim_bg to blend_color for better clarity.
=> refactor: move utility functions to utils module

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua
- Make chat buffer non-modifiable by default and only allow modifications during content updates and after response is finished
- Join response progress undos together so user can undo whole ask/response at once
- Rerender headers in chat window on text change automatically, which means that when users accidentally edits the separators in buffer the highlights do not break until next question is asked
=> fix: improve chat buffer rendering and state handling

lua/CopilotChat/chat.lua
Prevents issue when rerendering is not triggered due to buffer being hidden but still being updated
=> fix: rerender chat after opening as well

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/init.lua, lua/CopilotChat/select.lua
Adds new register context that allows accessing vim register contents in chat
and improves selection handling by:
- Making selection fields required instead of optional
- Improving unnamed register selection to include buffer context
- Deprecating clipboard selection in favor of register context
- Adding proper mark setting for better selection tracking
- Supporting array of default contexts in config
The register context supports all standard vim registers and provides a UI
for selecting them when used. This makes accessing clipboard and other
registers more intuitive.
=> feat: add register context and improve selection handling

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
Enhance selection validation by properly checking for existence of start_line and end_line values. This prevents potential nil access errors when handling invalid selections.
Previously the code only checked if end_line was greater than 0, which could lead to errors if start_line or end_line were nil.
=> fix: improve selection validation checks

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua
Add new command to show context of the current chat message that maps to `gc` by default. Unify existing overlay windows into single overlay implementation and improve resolution of prompts and embeddings by extracting them into separate functions. The overlay now also shows truncated preview of longer files.
This change improves debugging experience when working with contextual prompts by allowing users to inspect what files and contexts are being used for the current prompt.
=> feat: add show context command for Copilot Chat

lua/CopilotChat/chat.lua
Add validate() method to Chat class that ensures the window buffer stays in sync. This prevents potential issues where the window could show incorrect buffer content by validating and resetting the buffer if needed.
=> feat: add buffer validation for chat window

lua/CopilotChat/chat.lua
Sets menuone, noinsert and popup as default completion options for the chat buffer to improve the autocompletion experience in the chat window.
=> feat(chat): set default completion options for chat buf

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Replaces ad-hoc embedding handling with a new OrderedMap data structure to maintain insertion order and prevent duplicates. This change improves code organization and performance by:
- Adding new OrderedMap utility class for ordered key-value storage
- Refactoring embedding collection to use OrderedMap
- Optimizing file token budget allocation to process from back to front
- Adding threshold for multi-file embeddings processing
- Preserving command prefixes in prompt processing
The changes make the code more maintainable and efficient when handling multiple file contexts in chat interactions.
=> refactor: improve embedding handling with ordered map

README.md, lua/CopilotChat/chat.lua
The completeopt buffer option was being set unconditionally, which could cause errors in older Neovim versions. This change adds a version check to ensure the setting is only modified on Neovim 0.11.0 and newer versions.
=> fix: guard completeopt setting behind nvim-0.11.0 check

lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Previously, getting window cwd required switching active windows which could
cause unwanted side effects. Now, the cwd is stored in window variables and
updated via DirChanged autocmd, making the operation more reliable and
avoiding window switching.
Closes #582
=> fix: improve window CWD handling

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Clear chat prompt logic has been moved to dedicated method in Chat class to improve code reusability and maintainability. Window local cwd detection has been simplified and now uses VimEnter/WinEnter events instead of DirChanged for more reliable current working directory tracking.
=> fix: improve chat prompt clearing and cwd detection

lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Turns out nvim_win_get_var was a drama queen, throwing exceptions
whenever it couldn't find its precious variable - like a toddler having
a meltdown when they can't find their favorite toy.
Switched to vim.w, the more chill cousin who just returns nil and goes
about their day when something's missing. Now our code won't have an
existential crisis just because a directory hasn't changed.
No more exception-al behavior, just peaceful, quiet coding.
---
(Having some fun with system prompts, trying to make it act like a comedian.
I'm very new to prompt engineering, as you can tell by this not being all that
funny.)
Anyway, disclaimer: this is partially untested. It fixes the exception which
happens if the dir hasn't changed, but I haven't tested actually changing the
dir because I don't know …
=> fix: stop window vars from throwing tantrums

lua/CopilotChat/chat.lua
Replace pattern matching with direct string comparison when detecting section headers in chat rendering. This change improves performance by avoiding unnecessary regex operations for simple string equality checks.
=> perf: optimize chat section detection

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua, lua/CopilotChat/spinner.lua
The help display and token count mechanism has been improved by:
- Moving token count display to be part of the help message
- Adding clear help functionality to overlay
- Cleaning up finish function parameters and logic
- Using dedicated namespace for spinner
- Simplifying help display logic in chat rendering
This change makes the UI cleaner and more consistent by integrating the token count into the help display system instead of showing it separately.
=> feat: improve help display and token count visibility

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
- Fix loading of auto-insert-mode config
- Fix auto-insert mode to only trigger when buffer is modifiable
- Remove unnecessary undojoin command in chat append
- Simplify stop/reset logic and remove scheduling wrapper
- Fix return to normal mode function to always call stopinsert
=> fix: improve chat window handling and auto-insert behavior

README.md, lua/CopilotChat/actions.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Rewrite prompt resolution to use recursive approach with depth limiting to prevent infinite loops. Move shared config types to separate class and improve type definitions. Clean up prompt handling by removing kind field and simplifying system/user prompt distinction. Fix order of returned values in resolve_prompts to match usage.
Also includes some code formatting fixes and reordering of config options for better readability.
=> refactor: improve prompt resolution handling and cleanup types

lua/CopilotChat/init.lua
Sort completion items consistently by first comparing their kinds, and when kinds are equal, sort them alphabetically by word. This provides a more predictable and user-friendly order in completion menus.
=> feat: sort completion items by kind and word

README.md, lua/CopilotChat/actions.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
Split the plugin configuration into two parts:
- Static config that can only be set via setup()
- Shared config that can be passed as runtime parameters to functions
This improves the configuration management by clearly separating configuration parameters that should be set only once during setup from those that can be modified during runtime. Also renamed no_chat option to headless for better clarity.
=> refactor(config): split config into static and shared parts properly

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/ui/overlay.lua, lua/CopilotChat/ui/spinner.lua, lua/CopilotChat/utils.lua
This commit reorganizes the code to handle truncation of large files and embeddings in a more consistent way. The changes include:
- Moving ordered_map implementation to top of utils.lua
- Centralizing truncation logic for embeddings with BIG_EMBED_THRESHOLD
- Simplifying outline truncation by moving it to embedding generation
- Updating class type definitions to be more consistent
- Removing duplicate code related to truncation handlers
The main goal is to make the codebase more maintainable by having truncation logic in appropriate locations rather than scattered across different files.
=> refactor: move embed truncation logic to proper places

lua/CopilotChat/context.lua, lua/CopilotChat/init.lua
The changes improve how prompts are embedded and ranked in the context system:
- Move prompt embedding to after initial data ranking to maintain correct ordering
- Fix log output to show correct embedded query content
- Trim whitespace from resolved prompts to improve matching
This ensures more accurate context retrieval and better prompt handling in the chat system.
=> fix: improve prompt embedding and ranking

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua
The commit improves the outline building functionality by:
- Adding field_declaration and record_declaration to outline types
- Removing redundant comment handling logic to simplify the code
- Adding proper type annotations for functions
- Extracting reusable functions for getting node names and signatures
- Adding embedding type definition to copilot class
=> refactor(context): simplify outline building and add typing

lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
This commit improves handling of sticky prompts by:
1. Using proper line splitting and startswith check instead of gmatch
2. Fixing the sticky prefix removal to only match start of line
3. Ensuring proper rendering before section/block detection
The changes make sticky prompts more reliable and fix edge cases in the UI rendering.
Closes #614
=> fix: improve sticky prompt handling and section detection

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/utils.lua
Replace plenary async operations with vim.uv async APIs where possible to improve performance and reduce dependencies. This includes:
- File operations now use vim.uv.fs_* functions
- Simplified files context provider to remove pattern matching
- Moved curl helpers to utils module
- Cleaned up tiktoken loading process
The file operations are still partly synchronous and marked with FIXME comments for future async migration.
=> refactor: migrate to uv async for file operations

lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua, test/plugin_spec.lua
Remove redundant vim.schedule calls and replace them with more efficient async scheduler utilities. This includes:
- Using async.util.scheduler() instead of vim.schedule wrapper functions
- Consolidating scheduler calls to reduce overhead
- Utilizing vim.schedule_wrap for progress callbacks
The changes make the code more maintainable and potentially improve performance by reducing unnecessary scheduler invocations.
=> refactor: optimize vim scheduler usage in chat module

lua/CopilotChat/copilot.lua
Add detailed debug logging for Copilot HTTP response status, body and headers to help with troubleshooting API communication issues.
=> fix: add debug logging for Copilot HTTP responses

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/utils.lua
Replace synchronous io.popen git diff call with asynchronous vim.system in context.lua. Add async scheduler to token fetching and introduce a new utils helper for system calls.
This change improves overall plugin performance by making git operations asynchronous and following Neovim's best practices for system calls.
=> refactor(context): replace io.popen with vim.system

lua/CopilotChat/copilot.lua
Remove unnecessary async scheduler call from get_cached_token function and move github_token initialization to constructor to avoid repeated calls. This change improves the performance by reducing overhead of token retrieval.
=> perf: optimize GitHub token handling and remove scheduler

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/utils.lua
The files context provider now supports two modes:
- 'list' (default) - includes only filenames in the workspace
- 'full' - includes both filenames and their content
This change provides more flexibility when needing full context from workspace files. The implementation also adds proper filetype detection and filtering for files to ensure only text files are included.
Closes #360
=> feat(context): add full file content support for files

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua
Implement adaptive batch sizing and content thresholding for embeddings to handle API failures more gracefully. This change:
- Removes manual token counting in favor of API-driven feedback
- Adds progressive batch size reduction when requests fail
- Implements content threshold reduction for large files
- Adds proper curl failure handling with --fail-with-body
- Increases multi-file threshold from 3 to 5 files
- Adjusts embedding thresholds for better performance
=> refactor(copilot): improve embedding reliability

lua/CopilotChat/context.lua, lua/CopilotChat/ui/debug.lua
Previously, the debug info window could be opened multiple times and didn't properly handle async operations. This commit:
- Makes buffer parameter optional in context.buffer()
- Adds proper window cleanup on close
- Wraps debug info building in async operation to prevent UI blocking
- Stores window number reference to manage single instance
=> fix: improve debug info window handling

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/select.lua, lua/CopilotChat/ui/debug.lua, lua/CopilotChat/utils.lua
Refactor context.lua to introduce file caching mechanism and improve code organization around file handling. The main changes include:
- Add file caching to avoid reprocessing unchanged files
- Move outline generation logic into separate build_outline function
- Consolidate embed type definitions into context.lua
- Remove duplicate type definitions from copilot.lua
- Optimize file loading with new get_file helper function
Closes #628
=> refactor(context): optimize file loading with caching

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Replace vim.inspect usage with new make_string utility function to provide more consistent and cleaner logging output across the codebase. This makes logs more readable and uniform when handling both simple values and complex data structures.
The changes include:
- Add make_string utility function for standardized string conversion
- Replace vim.inspect calls with direct logging or make_string
- Improve error message formatting for better readability
=> fix: improve logging output format and consistency

lua/CopilotChat/init.lua
Previously errors in the async chat operation were not properly caught and handled, which could lead to silent failures. This change adds proper error handling using pcall and displays errors to users when not in headless mode.
=> fix: add error handling to chat async operation

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Consolidates multiple info display commands (show_system_prompt,
show_user_selection, show_user_context) into two more comprehensive
commands:
- show_info (gi): displays model, agent and system prompt
- show_context (gc): shows selection and embeddings
This change improves UX by providing more organized and complete
information when inspecting chat context and configuration.
BREAKING CHANGE: Removed show_system_prompt (gp), show_user_selection (gs)
and show_user_context mappings in favor of new unified commands.
=> refactor: unify info display into show_info and show_context

lua/CopilotChat/ui/debug.lua
Add a null check for buf.symbols before attempting to iterate through the symbols array in debug info builder. This prevents potential errors when symbols are not available for the current buffer.
=> fix: add null check for buffer symbols

lua/CopilotChat/ui/debug.lua
Add empty lines between sections in debug info to make the output more readable and easier to scan visually.
=> style: improve debug output readability

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/health.lua, lua/CopilotChat/utils.lua
Adds new URL context that allows including content of URLs in chat context using lynx text browser. This enables users to reference external content in their chat prompts.
Also improves documentation around optional dependencies and fixes curl utility functions to work with optional parameters.
=> feat: add URL context support using lynx

README.md
Improve README formatting by making the optional dependencies more consistent and add information about the :CopilotChat<PromptName> command to the list of available commands.
- Make (Optional) prefix consistent across all dependencies
- Remove trailing period from Copilot chat setting requirement
- Add documentation for :CopilotChat<PromptName> command usage
=> docs: improve README formatting and add prompt command info

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua, lua/CopilotChat/health.lua
Previously, lynx was required for the URL context to work. This change makes lynx optional by adding a fallback to curl when lynx is not available or fails. The fallback implementation includes HTML content cleanup to provide readable text.
When lynx is available, it will be used for better text formatting, but the URL context will still work without it using the curl fallback.
=> feat: make lynx optional for URL context

lua/CopilotChat/init.lua
Change CopilotChatSpinner highlight group to link to DiagnosticInfo instead of CursorColumn for better visual consistency with other UI elements.
=> style: link spinner highlight to DiagnosticInfo

lua/CopilotChat/copilot.lua
Remove unnecessary info-level logging from agent fetching and policy enabling functions to reduce log noise. Debug information is still preserved via trace logging.
=> refactor: remove redundant log messages

lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/select.lua
Move the CopilotChat.source type definition from config.lua to init.lua and update all references to use the new type location. This improves type organization by placing the core source type definition in the main module file.
=> refactor: move source type to init.lua

lua/CopilotChat/config.lua, lua/CopilotChat/context.lua
Move buffer list filtering logic from config.lua to a new dedicated function `buffers()` in context.lua for better code organization and reusability.
=> refactor(context): extract buffer list logic to new function

README.md
Update incorrect context name from `files:content` to `files:full` in the README documentation to match the actual implementation.
=> docs: update files context name in README.md

.github/workflows/ci.yml, README.md
- panvimdoc generates help tags for h1 and h2 headers so make sure everything
that should have a help tag is h1 or h2 and everything else is h3+
- remove contributors emoji so the generation is better for the help tag
=> docs: Improve README structure so generated vimdoc is better

README.md
Add example showing how to access the current chat configuration and print the model name, helping users understand how to retrieve configuration values at runtime.
=> docs: add config retrieval example to README

README.md
Update GitHub Actions workflow and documentation links to their correct paths. This ensures that the badge links in README.md point to the proper destinations.
- Fix GitHub Actions workflow badge link
- Fix documentation badge link to use relative path
=> fix: correct badge links in README.md

README.md
Github already has toc just forgot it exists:
=> docs: Remove toc

README.md
=> docs: add mention about clause availability

README.md
Update the documentation to reflect the correct list of buffers that can be customized by users: copilot-chat, copilot-diff, and copilot-overlay. Remove mention of copilot-system-prompt and copilot-user-selection which are no longer used.
=> docs: update list of customizable buffers

.github/workflows/ci.yml
Update GitHub Actions workflow configuration to run pandoc to vimdoc conversion on the main branch instead of the canary branch.
This change ensures documentation is properly generated and updated when changes are merged into the main branch.
=> ci: update pandoc workflow to run on main branch

lua/CopilotChat/copilot.lua
Enhance the stream parsing logic by better handling finish_reason and error conditions. Changes include:
- Add finish_reason check to properly close streams
- Improve data prefix trimming in stream messages
- Pass job context to parse_line for better error handling
- Add debug logging for stream completion
=> fix: improve stream parsing and error handling

lua/CopilotChat/context.lua
Move file list chunking before content processing to ensure consistent ordering of operations and improve code flow. Also increase TOP_RELATED constant from 20 to 25 for better related files detection.
The chunking logic now runs first, followed by optional content processing, which makes the code more maintainable and logical in its execution order.
=> refactor: optimize file list processing order

lua/CopilotChat/init.lua
When opening chat and asking questions, ensure proper config inheritance by deep extending chat state config with provided config and global config. Also move config handling before early returns to maintain consistency.
Closes #676
=> fix: correct chat config handling

lua/CopilotChat/init.lua
Add nil check for state.source by providing empty table as default value to prevent errors when source is not initialized. This ensures the code handles undefined source gracefully.
=> fix: add default empty table for state.source

lua/CopilotChat/integrations/snacks.lua
This adds an integration for the new snacks.nvim picker to be used when picking prompt actions with prompt preview:
=> feat: add snacks.nvim picker integration

lua/CopilotChat/init.lua
fixes https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/703
This change ensures we set the source in headless mode so it can still be used by callback/prompts.
For example, opening nvim and immediately running 
```lua
local chat = require("CopilotChat")
chat.ask("/Review", {
headless = true,
})
```
will now work!
whereas before, it gave the following error
```
Error executing vim.schedule lua callback: ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...re/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/config.lua:330: attempt to index local 'source' (a nil value)
stack traceback:
[C]: in function 'error'
...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next' …
```
=> fix: headless mode causing nil source

lua/CopilotChat/integrations/telescope.lua
Added theme options to the M.pick function to allow selection of dropdown, ivy, and cursor themes.
=> feat: Add theme options to select Telescope themes

README.md
Add a `lazy.nvim keys` keybinding to the `README.md` `Tips` section, following #730.
=> docs(readme): add perplexity search keybind to tips

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua
This commit adds support for the quickfix list context in CopilotChat. The quickfix context allows including the contents of files listed in the quickfix list as part of the chat context.
The implementation includes:
- New quickfix context type in config.lua
- Function to extract and process quickfix list files
- Updated documentation in README.md with the new context type
=> feat: add quickfix list context support

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Split existing quickfix mapping (gq) into two separate mappings:
- gqa: adds all chat answers to quickfix list
- gqd: adds all code diffs to quickfix list (previous gq functionality)
This allows for easier navigation between different parts of the chat history, particularly when reviewing AI responses.
=> feat: add quickfix list support for chat answers

lua/CopilotChat/context.lua
We use files not booleans.
This pull request includes a small change to the `lua/CopilotChat/context.lua` file. The change modifies the `quickfix` function to use `vim.tbl_keys` instead of `vim.tbl_values` when processing `unique_files`.
* [`lua/CopilotChat/context.lua`](diffhunk://#diff-2d1d203284a8d057142c9904421ec216f7b8dafc696915f24f3552608dfb5e75L562-R562): Changed the `quickfix` function to use `vim.tbl_keys` instead of `vim.tbl_values` when iterating over `unique_files`.
=> context: Fix bugs.

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/diff.lua
Add new `full_diff` option to show_diff mapping which allows showing a full diff view instead of unified diff view. When enabled, it will show the modified file content side by side with original file using Vim's built-in diff mode.
The full diff mode provides better visualization of changes and allows using Vim's diff navigation commands to review changes.
Closes #705
=> feat(diff): add option to show full diff with diff mode

README.md
Add documentation for new configuration options:
- `mappings.yank_diff.register` for customizing yank register
- `mappings.show_diff.full_diff` for toggling between full and unified diff display
Update examples section to demonstrate the new configuration options.
=> docs(readme): add config options for mappings

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/context.lua
Allow viewing diffs for specific commits by passing commit hash/reference to the git context. This extends the existing git context functionality which previously only supported staged and unstaged changes.
The change includes:
- Updated documentation in README.md to reflect new git context options
- Modified context handler to support commit references
- Updated config description to mention commit number support
=> feat(context): add support for commit-specific git diffs

lua/CopilotChat/utils.lua
Was having a hard time to understand why typescript files `.ts` are not being taken to the context through `#file:`.
Seems to be because of this issue with `vim.filetype.match`: https://github.com/neovim/neovim/issues/27265
Copied `GitMurf`'s fix from that GH issue, which temporarily solves it till it's properly fixed on the neovim side.
=> fix: typescript file type matching

lua/CopilotChat/copilot.lua
The Copilot API returns a `finish_reason` field that indicates why the response stopped. This commit adds this information to the UI, so the user knows why the response stopped.
If the reason is `stop`, it means that the response was finished normally, so we don't need to show any message.
Closes https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/711
=> feat: Report early stop reason to the UI

lua/CopilotChat/init.lua
It should always be explicitely triggered when pressing tab only
Closes #762
=> fix: do not auto trigger context input on text changed

.github/workflows/deploy-gh-pages.yml, Gemfile, _config.yml, lua/CopilotChat/config/providers.lua
Adds proper Jekyll configuration for GitHub Pages with midnight theme and GitHub Flavored Markdown support. Fixes async token loading in providers to prevent UI blocking.
- Add Jekyll config with GFM and midnight theme
- Set production environment for Jekyll build
- Fix async GitHub token loading with scheduler
=> fix: improve github pages deployment config

.github/workflows/deploy-gh-pages.yml, _config.yml, index.html
Replace Jekyll-based documentation with Docsify for simpler and more flexible documentation setup. This change:
- Removes Jekyll configuration and build step from GH Pages workflow
- Adds basic Docsify setup with search and image zoom plugins
- Creates .nojekyll file to disable GitHub Pages Jekyll processing
The migration provides a more maintainable documentation system that works better with single-page documentation sites.
=> feat: migrate from Jekyll to Docsify

README.md
Change all H3 (###) section headers to H2 (##) for better document structure and consistency. This improves the readability and navigation of the README.md file by maintaining a proper heading hierarchy.
Remove roadmap section as it was outdated and contained only two generic items.
=> docs(readme): normalize heading hierarchy

README.md
Replace the old documentation badge with a new one pointing to the GitHub Pages site at copilotc-nvim.github.io. This provides better visibility for the project's documentation.
=> docs(readme): update documentation badge link

lua/CopilotChat/context.lua
Ensures proper async scheduling when accessing vim registers by adding async.util.scheduler() call before register operations.
=> fix: add scheduler in register function

lua/CopilotChat/config/providers.lua
Removes unused policy field from provider model configuration and reorganizes tokenizer field placement for better code organization. This change simplifies the provider model structure by removing unnecessary state tracking.
=> feat: remove policy field from provider configuration

index.html, lua/CopilotChat/client.lua
Changes the docsify theme from vue to simple-dark theme and adds error logging for failed embedding requests. This improves readability for users who prefer dark mode and helps with debugging embedding issues.
- Replace vue.css with theme-simple-dark.css
- Add docsify-themeable script
- Add debug logging for embedding errors
=> feat: switch documentation to dark theme

lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua
Remove unnecessary HTTP headers and standardize header casing across the codebase. This simplifies the header management by:
- Removing unused machine ID and session ID tracking
- Using consistent header casing (capitalized)
- Removing redundant version headers
- Simplifying authorization header format
These changes make the code more maintainable while preserving core functionality.
Source: https://github.com/zed-industries/zed/blob/ad43bbbf5eda59eba65309735472e0be58b4f7dd/crates/copilot/src/copilot_chat.rs#L324
=> refactor: simplify HTTP headers

lua/CopilotChat/config/providers.lua
Fix code style consistency by adding a trailing comma in the headers table definition in providers.lua
=> style: add missing trailing comma in headers table

lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua
Makes the provider handling more robust by:
- Making get_token optional for providers
- Adding error handling for model and agent fetching
- Ensuring unique model/agent IDs by appending provider name on conflicts
- Sorting providers for consistent order
- Removing provider suffix from model name before request
These changes improve reliability when multiple providers are configured and prevent conflicts between models/agents with the same IDs from different providers.
=> fix: improve provider handling and model uniqueness

lua/CopilotChat/client.lua
The change modifies how provider suffix is added to agent/model IDs to ensure consistent handling across the codebase. Now the provider name is appended to the ID instead of being prepended, and the suffix is properly stripped when making API calls.
=> fix: change agent/model id provider suffix format

README.md, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/diff.lua, lua/CopilotChat/utils.lua
Restructures the codebase by moving mapping-related callback functions from init.lua to config/mappings.lua. This improves code organization and makes mapping configuration more self-contained.
- Adds callback field to mapping config class
- Moves all mapping callback functions to their respective mapping configs
- Extracts shared functions to utils module
- Simplifies mapping registration by using callback field
=> refactor(mappings): move callback functions to mapping config

README.md
Reorganize README.md sections for better readability and navigation:
- Convert list sections to tables for clearer information presentation
- Improve formatting and structure of configuration examples
- Add clear section headers and better organization of content
- Update API reference section with cleaner formatting
- Consolidate examples and tips into a single section
- Fix minor typos and inconsistencies throughout the document
=> docs: reorganize and improve README.md readability

README.md
The change fixes the ollama provider by using the proper module import path 'CopilotChat.utils' instead of directly accessing the local cutils module. This ensures consistent module resolution across the codebase.
=> fix(ollama): use correct module import path

README.md
The system_prompt configuration option was incorrectly referencing the COPILOT_INSTRUCTIONS table directly. This change updates it to correctly reference the system_prompt field within that table.
=> fix: update system_prompt config reference

README.md
Make get_models headers parameter required for non-embedding providers and improve documentation formatting by updating section header level for better readability.
=> docs(provider): update ollama provider interface docs

README.md, lua/CopilotChat/client.lua, lua/CopilotChat/context.lua
Previously the code would error when embeddings provider was not found. Now it gracefully handles missing providers by skipping embeddings calculation. This improves reliability when custom providers don't implement embeddings support.
Also adds null check for spatial distance calculation and moves provider interface documentation before the example in README.md for better readability.
=> fix(embeddings): improve embedding resolution reliability

lua/CopilotChat/config/providers.lua
Change the parameter name from 'inputs' to 'input' in the Copilot embeddings provider to match the OpenAI API requirements for text embeddings endpoint.
=> fix: update embeddings input parameter name

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/config/prompts.lua
Update yank functionality to use closest chat block instead of diff content. Add proper type annotations for contexts and prompts tables. Clean up unnecessary comment and improve type definition for callback function.
This change makes the yank feature more intuitive by copying the actual chat block content rather than diff changes.
=> refactor(chat): improve yank functionality and types

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/init.lua
The changes optimize file scanning by using a dedicated scan_dir utility with gitignore support and improve async handling in context input processing:
- Replace vim.fn.glob with optimized scan_dir utility
- Add gitignore respect to file scanning
- Fix potential UI freezes by properly handling async context input
- Ensure scheduler is called before UI operations
Closes #690
=> perf: improve file scanning and async input handling

lua/CopilotChat/config.lua
I might be wrong but I believe the type annotation for this one was a mistake based on the types from other fields.
Noticed this because I was getting the spurious warning shown below:
=> fix: type annotation of config.providers

lua/CopilotChat/client.lua, lua/CopilotChat/config/contexts.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/context.lua, lua/CopilotChat/init.lua
The client module has been refactored to be stateless by making it a singleton and moving provider initialization to a separate method. This simplifies the overall architecture and makes the code more maintainable.
Additional changes:
- Improved reference handling and generation
- Updated header naming convention for Copilot requests
- Fixed embedding context resolution to pass proper params
- Removed redundant client state from main module
=> refactor: make client module stateless

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/init.lua
The model parameter was unused in context resolution functions and has been removed to simplify the API. This change affects both the type definition and implementation of context resolving functions.
=> fix: remove unused model param from context resolving

lua/CopilotChat/init.lua
Remove selected_model parameter from resolve_embeddings function call as it's no longer needed. This simplifies the function signature while maintaining the same functionality.
=> refactor: simplify resolve_embeddings function signature

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/context.lua, lua/CopilotChat/utils.lua
Introduces similarity thresholds and file limits to improve matching performance:
- Add MIN_SYMBOL_SIMILARITY (0.4) and MIN_SEMANTIC_SIMILARITY (0.3) thresholds
- Implement max_files limit (1000) for directory scanning
- Refactor ranking algorithms to filter by similarity instead of taking top N
- Improve symbol matching to use normalized similarity scores
These changes help prevent performance issues with large codebases while maintaining matching quality by using similarity-based filtering.
=> perf: improve file and context matching performance

lua/CopilotChat/config/providers.lua
Previously, headers were hardcoded in the get_models function which made the code less flexible. This change passes headers as a parameter, allowing for proper header configuration when making API calls to the GitHub models endpoint.
=> fix: use proper headers for GitHub models API call

lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
The references section in the chat UI has been improved by moving it above the help section and displaying it with proper highlighting using virtual lines. This change also fixes a diagnostic warning in the sticky prompt handling code.
Changes:
- Move references section above help section
- Use virtual lines with highlighting for references display
- Add diagnostic disable comment for param-type-mismatch warning
=> fix: improve references display in chat UI

lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua
Currently token counting and limiting messages is enforced for all chat providers, but this should be optional as not all chat providers support token limiting. This change makes token counting optional and only enabled when max_tokens and tokenizer are provided in model config.
The types in providers.lua have also been updated to reflect the optional nature of these fields.
Closes #812
=> fix: make token counting optional in chat client

lua/CopilotChat/client.lua, lua/CopilotChat/context.lua
Adds MIN_RESULTS constant to guarantee at least 3 results are returned when searching for related code context, even if they don't meet the similarity threshold. This improves the quality of contextual responses by preventing cases where too few results would be returned.
Also adds score normalization for symbol-based search and debug logging for generated messages.
=> fix(context): ensure minimum number of search results

lua/CopilotChat/context.lua
The change removes the conditional check that filtered out entries with zero scores. This ensures all entries are included in the results array, allowing for proper normalization of scores across the entire dataset.
=> fix: include entries with zero score in results

README.md, lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua
Simplifies provider interface by combining get_token and get_headers into a single get_headers method that returns both headers and expiration time. This reduces complexity and removes the need to pass tokens between functions.
Updates documentation to reflect the new provider interface and adds better type hints for provider methods. Also extracts copilot embeddings provider into a separate module.
=> refactor!: simplify header authentication

lua/CopilotChat/client.lua, lua/CopilotChat/ui/chat.lua, lua/CopilotChat/utils.lua
This commit introduces a new utility function `empty()` that checks if a value is empty. This function handles nil values, empty tables, and whitespace-only strings.
The function is used to improve empty value checking across the codebase, replacing direct nil checks with the more robust empty() function.
Changes:
- Add utils.empty() function
- Update client.lua to use empty() for response validation
- Update chat.lua to use empty() for content checks
=> feat: add utils.empty() function for checking empty values

lua/CopilotChat/client.lua
Previously the selection messages were not being added to the final generated messages array when embedding messages were not limited. This fix ensures selection messages are properly included in the output.
=> fix: add missing selection messages to generated output

README.md
To keep the main README.md clean and maintainable, move the examples, tips, and external providers sections to dedicated wiki pages. This improves documentation organization while keeping the same information accessible.
The following sections were moved:
- Ollama provider example -> External Providers wiki page
- Tips and Examples -> Examples and Tips wiki page
=> docs: move examples and providers to wiki

lua/CopilotChat/init.lua
When resetting the chat, properly clean up any
remaining selection marks and highlights from the source buffer. This prevents leftover visual indicators from persisting after the chat session ends.
=> fix: clear chat selection marks and highlights on reset

README.md, lua/CopilotChat/health.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua, lua/CopilotChat/utils.lua
This commit adds syntax highlighting for keywords in the chat buffer and improves documentation around buffer types and highlights. It also:
- Removes the development version check in health.lua in favor of stable version check only
- Removes is_stable() utility function as it's no longer needed
- Updates CopilotChatSpinner highlight to use DiagnosticHint
- Improves README documentation for buffer types and highlight groups
The highlight keywords are populated from completion items and are updated when entering the chat buffer.
=> feat: add keyword highlights and improve buffer docs

lua/CopilotChat/init.lua
The commit fixes an issue with syntax highlighting patterns where special regex characters were not properly escaped, leading to incorrect highlighting of keywords containing characters like dots, brackets or asterisks.
=> fix: properly escape highlight pattern chars

lua/CopilotChat/client.lua, lua/CopilotChat/config/contexts.lua, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
The chat history was previously managed in the UI layer through parsing of rendered chat sections. This change moves the history management directly into the client layer for better separation of concerns.
Key changes:
- Add history field to Client class to store conversation history
- Remove parse_history from Chat UI class
- Update history handling in ask function to use client's history
- Maintain history only when not in headless mode
- Clean up header pattern matching in chat UI
- Fix diagnostic namespace to use consistent naming
Using chat buffer for client history had issues with resolving the history properly without stuff like #buffers etc so just go back to this solution.
=> refactor: migrate chat history from UI to client layer

lua/CopilotChat/context.lua
Modify scoring mechanism for buffer and file content contexts to better reflect their priority in the system. Remove redundant comment about score bonus.
Changes:
- Keep file content score at 0.2
- Set explicit buffer content score to 0.1
=> refactor: adjust context scoring values

lua/CopilotChat/context.lua, lua/CopilotChat/init.lua
When filtering embeddings, include previous user messages from chat history in the query string for better context matching. This helps improve the relevance of filtered embeddings by considering the full conversation context rather than just the current prompt.
The history inclusion can be disabled via the headless config option.
=> feat: include chat history in embedding query

lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua
Move last_message assignment before references check to ensure proper state tracking. Improve token usage and finish reason handling by adding fallback paths for different response formats from the Copilot API.
=> fix: update token handling and message ordering

README.md, lua/CopilotChat/config/contexts.lua, lua/CopilotChat/context.lua, lua/CopilotChat/utils.lua
Replace the basic list/full mode for files context with glob pattern matching support. This allows for more granular file filtering in the workspace using standard glob patterns like *.lua or **/*.js.
Split the original files context into two separate contexts:
- files: Returns file contents matching the glob pattern
- filenames: Returns only filenames matching the glob pattern
BREAKING CHANGE: The files context no longer accepts list/full as input options. Instead, it now expects a glob pattern. The old functionality has been split into two separate contexts: files and filenames.
=> feat!: add glob pattern support for file context

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/context.lua
Refactor the file context handling to use a more flexible search options approach. Instead of passing individual parameters, introduce a table-based configuration that can be extended with additional options.
This change makes the API more maintainable and extensible while keeping backward compatibility through the use of vim.tbl_extend.
=> refactor(context): improve file search options handling

lua/CopilotChat/config/providers.lua
Reorganize the copilot API request options to improve code clarity and maintain consistent behavior. Move stream, n, and temperature parameters into the non-O1 condition block where they belong.
=> fix: streamline copilot API request configuration

README.md
The "Overview" heading was unnecessary since the content below it directly describes the plugin's features and capabilities. This change improves the documentation flow by removing redundant hierarchy.
=> docs(readme): remove redundant overview heading

lua/CopilotChat/client.lua, lua/CopilotChat/init.lua
Enhance error reporting by preserving original error message when embedding requests fail instead of generic error. Clean up error message format by removing all file:line prefixes for better readability.
=> fix: improve error handling in embeddings and messages

README.md
Update README to reflect that CopilotChat.nvim supports Claude 3.7 Sonnet instead of the older 3.5 version.
=> docs: update Claude version to 3.7 in README

lua/CopilotChat/config/prompts.lua
Explicitly specify that code blocks in the modify prompt should be wrapped in triple backticks with the appropriate language. This ensures consistent formatting and better syntax highlighting for code snippets in responses.
=> docs(prompts): clarify code block format in modify prompt

lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Using vim.fs.normalize provides better path normalization across different operating systems. This change improves path handling consistency in file operations for the CopilotChat plugin.
There's also a typo fix in the function name from 'normalie' to 'normalize' at one location.
=> fix: replace vim.fn.expand with vim.fs.normalize

lua/CopilotChat/config/prompts.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/ui/spinner.lua, lua/CopilotChat/utils.lua
Replace deprecated vim.loop with vim.uv throughout the codebase. Remove custom file_exists utility function in favor of direct vim.uv.fs_stat calls for file existence checks.
This change improves code consistency and leverages built-in Neovim API functions rather than custom implementations.
=> refactor: replace vim.loop with vim.uv and simplify file checks

lua/CopilotChat/client.lua, lua/CopilotChat/utils.lua
Remove dependency on vim.fn.fnamemodify for file operations by using the more modern vim.fs API instead. This change:
- replaces vim.fn.fnamemodify with vim.fs.normalize for path comparison
- replaces vim.fn.fnamemodify with vim.fs.basename for filename extraction
- removes unnecessary async scheduler call in client.lua
Part of the effort to reduce reliance on Vim functions.
=> refactor: replace vim.fn functions with vim.fs equivalents

README.md
Add documentation section explaining how to configure various picker plugins to work with the :<input> functionality. Include setup instructions for fzf-lua, telescope, snacks.picker, and mini.pick.
=> docs: add picker integration instructions to README

README.md, lua/CopilotChat/init.lua
Add new command to easily browse and select from available prompt actions. This replaces the previous manual approach of requiring users to create actions through the API, providing a more user-friendly interface similar to the existing models and agents selection commands.
This is preparation to deprecated CopilotChat.actions and CopilotChat.integrations
=> feat: add CopilotChatPrompts command

README.md, lua/CopilotChat/init.lua
Updates the select_prompt function to accept an optional configuration parameter that can be passed to the ask method. This allows specifying additional settings like callbacks when using prompt templates.
Also improves documentation in README.md with more detailed explanations and examples of new functionality.
=> feat: add configuration to select_prompt function

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
Add new configuration option `references_display` that allows users to control how references are displayed in chat responses. Two modes are supported:
- 'virtual': displays references as virtual text (default)
- 'write': writes references directly into the chat buffer as markdown links
This gives users more flexibility in how reference information is presented and interacted with in the chat interface.
=> feat(ui): add option to control references display mode

lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua
Remove version field from models in favor of using just ID for model identification. Simplify model and agent listing with consistent sorting by provider and ID. Add model_picker_enabled flag for Copilot models to filter models that should appear in the model picker.
=> refactor(models): simplify model listing by using model_picker_enabled

lua/CopilotChat/utils.lua
Uses vim.fs.abspath in filename_same function to properly compare file paths that might be relative or have different representations but point to the same file.
=> fix: improve filename comparison with absolute paths

lua/CopilotChat/context.lua, lua/CopilotChat/select.lua, lua/CopilotChat/ui/chat.lua
Replace direct vim.fn.fnamemodify calls with utility functions for consistent filename handling across the codebase. This improves maintainability by centralizing path manipulation logic in utils module.
=> refactor: use utils functions for filename handling

lua/CopilotChat/init.lua
Add range support to the CopilotChatPrompts command to allow selecting text ranges when using the command, enhancing the flexibility of prompt selection.
=> feat: enable range support for CopilotChatPrompts

lua/CopilotChat/actions.lua, lua/CopilotChat/integrations/fzflua.lua, lua/CopilotChat/integrations/snacks.lua, lua/CopilotChat/integrations/telescope.lua
Add @deprecated tags to integration-related functions, directing users to use the newer CopilotChat.select_prompt interface instead. This improves API consistency and prepares for future changes.
=> feat(doc): mark integrations APIs as deprecated

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/context.lua, lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/utils.lua
Remove dependency on plenary.async.util.scheduler() by implementing a custom schedule_main() function that only schedules when necessary. This allows the plugin to work without requiring plenary's scheduling mechanism. Also fixes JSON decoding by ensuring response body is properly converted to string.
=> refactor: replace plenary scheduler with internal implementation

lua/CopilotChat/ui/chat.lua
This makes sure bufenter is called for `replace` layout properly
Closes #356
=> fix: switch buffer only after adjusting window options

lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
- Fix selection update to check for buffer equality
- Fix active chat detection to verify visibility first
- Fix window layout comparison to handle when config is nil
- Ensure config is set after window layout check to prevent errors
=> fix: improve chat window state handling

lua/CopilotChat/health.lua
Add health check to verify if vim.ui.select is using the default implementation or has been overridden by a custom implementation. This helps users identify if they could improve their experience by using a better picker integration.
Also improved formatting consistency in treesitter warning messages.
=> feat: add vim.ui.select health check

README.md, lua/CopilotChat/config/prompts.lua
Integrate code generation instructions directly into base prompt to simplify the system architecture. Remove the separate COPILOT_GENERATE prompt and update all references to it throughout the codebase.
The format instructions for code changes have been moved to the base prompt to ensure consistent formatting across all interaction modes. This change improves maintainability while preserving full functionality.
=> refactor: streamline system prompts architecture

lua/CopilotChat/config/prompts.lua
Change the structure of COPILOT_EXPLAIN and COPILOT_REVIEW prompts to lead with the role description before adding the base instructions. This makes the AI's role more prominent in the prompt and potentially improves response quality.
=> refactor: reorder role first in prompts

lua/CopilotChat/health.lua
Add a required setup verification step that warns users when the plugin hasn't been properly initialized. This helps troubleshoot common issues where users forget to call setup().
Also reorganize health checks by removing redundant header and moving the debug info suggestion to a more appropriate location.
=> feat(health): add setup check to health module

lua/CopilotChat/ui/chat.lua
When clearing the chat with the clear method, ensure the config is also reset to an empty table along with references and token counts. This prevents stale configuration from persisting across chat resets.
=> fix: clear config when resetting chat

lua/CopilotChat/ui/chat.lua
Previously, the Chat:clear() method was resetting the entire config object to an empty table, causing potential nil access errors when trying to access config.window.layout. This change:
1. Removes the config reset in the clear() method to preserve settings
2. Adds a nil check when accessing config.window to prevent errors
Closes #895
=> fix: prevent errors when accessing window config

lua/CopilotChat/utils.lua
When I use `**/*` pattern in the glob, it doesn't match the files in the subdirectories.
This is because `**/*` is first replaced with `.*` by `:gsub('%*%*/%*', '.*')`.
Then `:gsub('%*', '[^/]*')` kicks in and replaces that `*` with `[^/]*`. So, files in the subdirectories aren't getting matched.
Changed `:gsub('%*', '[^/]*')` to `:gsub('([^%.])%*', '%1[^/]*')`, so that `*` will only get replaced with it's not having a `.` before it.
=> fix(utils): `glob_to_regex` recursion matching

README.md, lua/CopilotChat/config/contexts.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/context.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Adds a new 'cmd' context that allows including the output of shell commands in chat context. This feature is useful for incorporating system information or command results directly into Copilot Chat.
The implementation:
- Updates documentation in README.md
- Adds new context entry in contexts.lua with input prompt
- Implements M.cmd() function with cross-platform support
- Adds status notifications for context operations
=> feat(context): add system context for shell command output

README.md, lua/CopilotChat/client.lua, lua/CopilotChat/config.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
This refactoring improves the CopilotChat plugin's state management by:
- Adding `insert_sticky` function to centralize sticky prompt management
- Creating `set_selection` to provide a cleaner API for selection handling
- Consolidating highlight management in `update_highlights`
- Standardizing function signatures and return values
- Improving `Chat:set_prompt` functionality
- Removing redundant code for better maintainability
BREAKING CHANGES:
- `M.resolve_prompt` now returns config first and prompt second
- `M.update_selection` removed in favor of new `M.set_selection` function
- `M.resolve_embeddings` renamed to `M.resolve_context`
- Selection setting now only configurable in global config, not per-operation
- `get_selection` no longer accepts a config parameter
- Selection handling …
=> refactor!: centralize sticky prompt and selection handling

README.md
The example in the README now better reflects the current API by removing the explicit selection parameter from the chat.ask configuration object.
=> docs: remove selection from chat.ask example

README.md
- Clarify that copilot provider is used for chat only, not embeddings
- Fix parameter syntax for get_headers function
- Correct reference path to select.lua
=> docs: update provider documentation and references

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/init.lua
Add configuration option to control whether model/agent/context are
remembered as sticky prompts when asking questions. This provides more
control over the persistence behavior.
Also added a 'grx' shortcut to clear all sticky prompts and changed
the toggle sticky keymap from 'gr' to 'grr' to avoid conflicts.
Closes #910
=> feat: add remember_as_sticky config option

README.md
Update README to clarify that selections for chat interactions can only be configured globally, not per-prompt.
=> docs(readme): update selections configuration info

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Make selection behavior configurable per-chat instance rather than only globally. This enables different selection strategies for different chat sessions while maintaining backward compatibility with the global configuration.
The selection field is moved higher in the config file for better visibility, and documentation is updated to reflect this change.
=> feat: allow per-chat selection configurations

README.md, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Mark async functions with proper `---@async` annotations to clearly indicate which functions require running in an async context. Update complete_items to return directly instead of using a callback pattern, improving code clarity and consistency with other async functions.
Functions now properly indicate when they require plenary.async.run in the API documentation.
BREAKING CHANGE: chat.complete_items() is now async instead of using callback
=> feat!: mark async functions with annotations

lua/CopilotChat/client.lua
Use ordered_map instead of an array to prevent duplicate references when the same file is referenced multiple times. This improves how references are handled and displayed in the response by:
- Including the current selection as a reference
- Ensuring each file appears only once in references
- Preserving reference order for consistent display
=> fix: eliminate reference duplication with ordered map

lua/CopilotChat/init.lua
Add a description field to prompt items and prefer displaying it over the raw prompt in the UI selection menu. This improves readability and user experience by showing more concise descriptions instead of potentially long prompts.
=> feat: add description field to prompt items

lua/CopilotChat/init.lua
When resetting Copilot Chat state, diagnostics weren't being cleared from the editor, which could lead to stale diagnostic information remaining visible. This change ensures diagnostics created by Copilot Chat are properly removed when stopping or resetting the chat.
=> fix: reset diagnostics when stopping Copilot Chat

README.md, lua/CopilotChat/client.lua, lua/CopilotChat/init.lua
Implement a memory system that automatically summarizes chat history to maintain context across long conversations while managing token usage. The system:
- Tracks conversation history and generates summaries when needed
- Includes summarized memory in system prompts for context
- Only loads recent messages after the last summarization point
- Optimizes token usage by accounting for memory in calculations
This reduces issues with context length limitations while preserving important information from previous interactions.
Inspired by:
https://github.com/yetone/avante.nvim/pull/1508
as it was pretty good idea, this PR takes it a bit further
=> feat: add conversation memory summarization

README.md, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/init.lua
Instead of sticky use context/system_prompt and rely on remember_as_sticky configuration for this to be remembered.
Also add support for resolving system_prompts by name
=> refactor(prompts): use proper fields for prompt settings

lua/CopilotChat/client.lua, lua/CopilotChat/config/mappings.lua
The commit fixes two issues:
- Updates direct access to history table to use self.history in the client module, removing redundant reassignment
- Adds a display for memory content in the chat overlay when available
This improves both correctness and usability of the Copilot Chat plugin.
=> fix: correct history storage in client

lua/CopilotChat/client.lua, lua/CopilotChat/init.lua
The memory summarization mechanism is now integrated directly into token budget handling instead of being called separately before each chat request. This improves efficiency by:
1. Only summarizing when we actually exceed the token limit
2. Properly recalculating token budgets after summarization
3. Adding consistent references tracking for embedded files
4. Moving job ID setting to after initial setup work is complete
This change makes memory management more robust and predictable while maintaining the same functionality.
=> refactor(memory): improve conversation memory management

lua/CopilotChat/client.lua
Instead of setting a single reference based on the selection object, the code now sets references for each message in the selection_messages array. This ensures that all selected files are properly included in the references map.
=> fix: update reference handling in selection messages

lua/CopilotChat/client.lua
Ensures that client memory is properly cleared when calling the reset method.
=> fix: clear memory when resetting the client

lua/CopilotChat/init.lua, lua/CopilotChat/ui/overlay.lua
The nvim_win_set_buf API doesn't automatically trigger BufEnter events when switching buffers. This was causing issues with proper state updates in the Copilot Chat UI when navigating between buffers.
This commit adds explicit BufEnter triggering and simplifies some related code to ensure proper event handling.
=> fix: manually trigger BufEnter when restoring buffers

lua/CopilotChat/utils.lua
The function now only calls 'stopinsert' when not already in normal mode, avoiding unnecessary command execution when already in normal mode.
=> fix(utils): optimize return to normal mode function

lua/CopilotChat/client.lua
According to SSE specification, lines starting with colon (:) are considered comments and should be ignored. This fixes the stream parser to properly handle these lines when processing responses from Copilot.
Closes #944
=> fix: ignore SSE comments in parsing stream response

lua/CopilotChat/ui/chat.lua
Return direct objects without wrapping them in new tables, since the original objects already contain all necessary information and fields. This simplifies the code without changing functionality.
=> refactor(chat): simplify section and block return values

lua/CopilotChat/config/mappings.lua
Use vim.api.nvim_win_call to properly handle buffer and window context when enabling and disabling diff mode. This ensures commands are run in the correct window context rather than affecting the current one, preventing unexpected side effects.
=> fix: improve buffer handling in diff view

lua/CopilotChat/config/mappings.lua
When displaying chat information, add the source filename to provide better context about where the chat was initiated from. This enhances debugging and improves user experience by making it clear which file is associated with the current chat session.
=> feat: show source information in chat info panel

lua/CopilotChat/init.lua
The update_source function now correctly determines the source buffer when running in headless mode by checking if we're in the chat window and using the appropriate window (previous window when in chat, current window otherwise).
This makes the plugin work properly in headless environments where window navigation behaves differently.
=> fix: improve source buffer selection for headless mode

README.md, lua/CopilotChat/config/contexts.lua, lua/CopilotChat/context.lua, lua/CopilotChat/health.lua, lua/CopilotChat/utils.lua
Adds ripgrep integration to improve search performance when scanning directories. Falls back to the existing scandir implementation when ripgrep is not available. Updates the configuration options to use more consistent naming and adds health check for the ripgrep dependency. Also cleans up installation instructions in README.
BREAKING CHANGE: Due to previous incorrect glob handling,
.lua patterns etc need to be specified as *.lua
=> feat(search)!: use ripgrep when available for file scanning

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/context.lua, lua/CopilotChat/utils.lua
Define and apply sensible default arguments for file scanning operations across the codebase. This adds a central configuration for max_count, max_depth and no_ignore parameters, making file operations more consistent.
The changes also improve the handling of max_count=0, which now correctly disables the file count limit rather than returning an empty result set.
=> feat: improve default file scanning arguments

README.md
The Tab key was incorrectly documented as working in normal mode for triggering/accepting the completion menu for tokens in the chat interface. This commit corrects the documentation to show that Tab is only available in insert mode.
=> fix(readme): remove Tab mapping in normal mode for chat

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Previously system_prompt could only be set using the full prompt object path. Now users can simply specify the prompt name as a string, and the system will resolve it to the actual prompt content automatically.
=> fix: allow using system prompt name as string

lua/CopilotChat/ui/chat.lua, lua/CopilotChat/ui/overlay.lua
Make both parameters to show_help optional and handle empty messages consistently. Remove redundant clear_help method in favor of calling show_help without parameters to achieve the same result.
=> refactor(ui): improve help message handling

lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua, plugin/CopilotChat.lua
Move commands, highlight definitions and treesitter registration from init.lua to a proper plugin/CopilotChat.lua file. This follows better plugin organization practices and ensures proper loading sequence.
Includes:
- Moving highlight definitions
- Moving commands (CopilotChat*)
- Moving autocmd for directory tracking
- Moving treesitter language registration
- Adding proper plugin loading guard
=> refactor: move commands and highlights to plugin file

lua/CopilotChat/ui/chat.lua
so we can match format like line:61 for single line diffs
=> fix: make second part of line matching in diffs optional

lua/CopilotChat/config/mappings.lua, lua/CopilotChat/ui/chat.lua
Enhance chat interface to support filtering sections by type (question or answer) and improve diff handling. The show_diff function now applies all diffs from the same file when in full_diff mode, providing a more complete view of changes.
=> feat(chat): add multi-diff support

lua/CopilotChat/config/mappings.lua
Remove print statements that were logging information about diffs being applied. These were likely added during development and are no longer needed in the codebase.
=> fix: remove debug print statements

lua/CopilotChat/config/mappings.lua
Moves the Memory section and adds a History section to the debug display, showing the conversation history in a truncated format with roles and first lines of content. This helps with debugging conversation context and tracking interaction flow.
=> feat(debug): add history info to debug output

README.md, lua/CopilotChat/init.lua
Prevents completion from triggering automatically in chat buffers when
required completeopt settings ('noinsert' and 'popup') are missing.
This resolves issues where completion would behave unexpectedly.
Also updates the warning message in README.md to clarify this requirement.
=> fix: disable auto-completion without proper completeopt

lua/CopilotChat/context.lua
Remove unnecessary `:lower()` calls when processing query text, as the trigram functionality already handles case normalization. Also added missing function documentation with parameter and return type annotations.
=> refactor(context): remove redundant toLowerCase calls

lua/CopilotChat/config/mappings.lua
When concatenating the modified array into a string, nil values could cause errors. This change adds a filter step to remove any nil values before concatenation, preventing potential runtime errors.
=> fix: filter nil values from modified array

lua/CopilotChat/client.lua, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/init.lua
Add system prompt section that instructs Copilot to request additional context using available context providers (#command:input format). Available context providers with descriptions are now included in the system prompt, making it easier for users to get relevant context for their queries.
The implementation passes context metadata to the LLM and includes proper formatting examples, ensuring that Copilot can effectively guide users to provide the right context when needed.
=> feat: add context provider command helpers to prompt

README.md
Add Mistral.ai to the list of supported external providers in multiple locations. Change link from wiki page to discussion page for external providers. Add informational note about AI's ability to request additional context from users.
=> docs: update external provider references and add AI info

lua/CopilotChat/client.lua
Improve error handling in fetch_models and fetch_agents by adding explicit authentication failure checks and using goto statements to continue loop execution when errors occur. This prevents the code from attempting to process invalid responses.
=> fix: guard against auth and API failures

.github/workflows/ci.yml, .github/workflows/release.yml, .pre-commit-config.yaml, lua/CopilotChat/config/contexts.lua, lua/CopilotChat/context.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Reorganize context handling by moving functionality from separate methods into more streamlined direct implementations. Replace context.buffer(), context.file(), etc. with exposed get_* methods that can be called directly.
The changes also improve notification transparency by showing which context is being resolved and with what input. This refactoring removes redundant code while maintaining the same functionality, resulting in a more maintainable codebase.
=> refactor(context): simplify context handling with direct methods

.github/workflows/release.yml
The package-name parameter wasn't required by the release workflow and has been removed to simplify configuration.
=> fix: remove unnecessary package-name parameter

lua/CopilotChat/client.lua, lua/CopilotChat/config/contexts.lua
Update the context prompt to consistently use backticks around all inputs for context providers. This makes the syntax more uniform and clarifies how to properly use context providers with spaces or special characters in input parameters.
Also clarifies the system context provider description to indicate it should be used judiciously.
=> refactor(context): standardize backtick syntax for providers

lua/CopilotChat/config/contexts.lua
Display error messages when system commands fail, showing the stderr output when available, or a generic failure message with the exit code when stderr is empty. Additionally, differentiate between successful and failed commands by using distinct filenames for better context in the Copilot Chat UI.
=> feat(system): improve system command context error handling

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Move window working directory logic from utils.win_cwd() to a method on the source object. This improves encapsulation by keeping the directory handling logic closer to the source object itself, while maintaining the same functionality.
The new approach uses a cwd() function on the source object that returns the appropriate directory value, simplifying how context providers access the current working directory.
=> refactor(context)!: move cwd handling to source object

lua/CopilotChat/config/mappings.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Refactor source buffer handling by exposing public API functions to get and set the source buffer. This allows greater flexibility for plugins or users who need to interact with the source buffer programmatically.
Also update the mapping type definitions to explicitly support false/nil values for disabling specific mappings, and add null checks to prevent errors when mappings are disabled.
=> feat: expose source buffer API and support disabling mappings

lua/CopilotChat/client.lua, lua/CopilotChat/config/contexts.lua
Better document the intended usage and behavior of context providers by:
- Adding "and their usage" to the main context providers heading
- Clarifying that URL provider should be preferred over system commands
- Making system command provider description more specific
=> docs: improve context provider descriptions

README.md, lua/CopilotChat/init.lua
The plugin previously required both 'noinsert' and 'popup' in completeopt for chat autocompletion to work. This change simplifies the requirements by only checking for 'noinsert', making the plugin more flexible and compatible with different Neovim configurations.
The code has been updated to:
- Remove popup requirement check in completion callback
- Remove automatic popup setting in completeopt
- Update documentation to reflect the changes
=> fix: remove requirement for popup in completeopt

README.md, lua/CopilotChat/init.lua
Allow chat autocompletion to work with either 'noinsert' or 'noselect' in completeopt for Neovim versions below 0.11.0. This provides more flexibility for users who prefer different completion behaviors.
=> feat: support noselect completeopt setting

lua/CopilotChat/client.lua
Lower the threshold for what is considered a big file from 2000 to 1000 line characters. This change helps improve performance by reducing the amount of content that needs to be processed for large files.
=> perf: lower big file threshold for better performance

README.md, lua/CopilotChat/config/prompts.lua
Extract the base prompt into COPILOT_BASE to allow custom prompts to be built on top of it. This enables users to extend the base behavior while maintaining core Copilot functionality.
The change includes:
- Renamed local 'base' to 'COPILOT_BASE'
- Exposed COPILOT_BASE in the returned prompts table
- Updated documentation to reflect the new base prompt
- Added example of extending base prompt in custom configurations
=> refactor: expose COPILOT_BASE prompt as base prompt

lua/CopilotChat/config/providers.lua
Instead of relying on model_picker_enabled rely on model.version again. This shows newer versions of models and hidden ones. This was removed in favour of model_picker_enabled in past but this approach is way better for usability.
=> feat: use version map again for resolving all copilot models

.stylua.toml, lua/CopilotChat/client.lua, lua/CopilotChat/config/contexts.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/context.lua, lua/CopilotChat/health.lua, lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/ui/chat.lua, lua/CopilotChat/ui/spinner.lua, plugin/CopilotChat.lua
Wraps context resolver in pcall to properly handle errors that might occur during context resolution. Previously, any error in the resolver would crash the entire operation. Now, errors are caught and logged, allowing the operation to continue with other context providers.
=> fix: add error handling for context resolution

lua/CopilotChat/init.lua
The code was incorrectly iterating directly over the resolved_embeddings array, which can lead to improper iteration in Lua. This commit fixes the issue by properly using ipairs() to ensure sequential iteration over numeric indices.
=> fix: use ipairs when iterating over resolved embeddings

README.md, lua/CopilotChat/client.lua, lua/CopilotChat/config.lua, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/init.lua
Add stream callback function to process tokens as they are received from Copilot while callback function is used to process the complete final response. Both functions can modify the text that gets displayed and stored in history.
This separates streaming token processing from final response handling, giving more control over how chat outputs are processed and displayed.
=> feat(chat): add streaming callback support

lua/CopilotChat/client.lua, lua/CopilotChat/init.lua
This change consolidates headless operation handling in CopilotChat by:
- Replacing summarize_history field with a unified headless field
- Conditionally displaying notification messages based on headless state
- Skipping current_job tracking in headless mode
- Preventing unnecessary UI updates when running headless
This creates a more consistent approach to handling headless operations throughout the codebase.
=> refactor: improve headless mode handling

lua/CopilotChat/context.lua, lua/CopilotChat/utils.lua
Improve outline generation performance by:
- Creating a separate outline cache to avoid redundant processing
- Converting M.get_outline to a local function with cleaner return values
- Generating outlines on-demand during embedding filtering
- Improving cache key generation with longer hash samples
- Refactoring file and buffer handling to simplify data flow
This change reduces processing overhead by only creating outlines when needed and avoiding duplicate work through targeted caching.
=> refactor: optimize code outline generation with caching

lua/CopilotChat/client.lua
Enhances readability of the context provider documentation by:
- Adding blank lines between each provider description
- Properly indenting multi-line descriptions with consistent spacing
- Maintaining consistent formatting across all provider help text
This change makes the help text more scannable and easier to read for users.
=> style: improve context provider help text formatting

lua/CopilotChat/init.lua
Include resolved embeddings data in error logs when context resolution fails. This additional information will help with debugging context resolution issues by providing more details about what was attempted.
=> fix: improve error logging for failed context resolution

lua/CopilotChat/client.lua
Update the context help text to be more concise by:
- Streamlining the introductory language
- Formatting examples for better readability
- Adding explicit guidelines for context command usage
- Clarifying expectations about context request handling
This change improves the prompt reliability
=> feat(context): improve context provider help text

lua/CopilotChat/config/contexts.lua
Update the system context description with detailed guidelines about when and how to use system commands safely. Remove redundant information from the URL context description.
This change helps guide the AI to use system commands only as a last resort and encourages using purpose-built contexts like URL instead.
=> feat(context): improve system command usage guidelines

lua/CopilotChat/utils.lua
Add several new file types to be excluded from scanning operations:
- Debug files (pdb, dSYM)
- ML/Data model formats (h5, pb, onnx, pt, safetensors, etc)
- 3D model formats (glb, gltf)
- Editor swap/temp files (swp, swo)
These exclusions will improve performance and relevance when scanning repositories by ignoring common binary and temporary files.
=> feat: add additional binary file types to scan exclusions

lua/CopilotChat/init.lua
When a job is cancelled, the response will be nil without any error. This change adds proper handling for this case by returning early when no response is available, preventing potential nil reference errors in the callback processing code.
=> fix: handle cancelled jobs in CopilotChat

README.md
Reorganize the API reference section in README.md to improve readability:
- Rename section headers to be more concise
- Group related functions with appropriate section headers
- Change variable naming in examples to be more descriptive
- Maintain consistent documentation style throughout
=> docs: improve API reference organization and clarity

README.md
The examples in README.md were incorrectly showing context providers with a # prefix in the code snippets. This commit updates the examples to show the correct format without the # character.
=> docs: remove # prefix from context provider examples

README.md
=> docs: add missing `,` in default config

lua/CopilotChat/client.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Properly handle headless mode in streaming and completion callbacks. Condition the job tracking logic on headless mode to prevent early termination of headless requests.
Refactor filetype detection to simplify the logic with more consistent handling of edge cases for sh and TypeScript files.
Closes #1026
=> fix: improve headless mode handling in callbacks

lua/CopilotChat/ui/chat.lua
This commit changes the split behavior to respect to the value of
&splitbelow and &splitright, which are both disabled by default.
This behavior was introduced in #950.
=> Respect &splitbelow and &splitright

lua/CopilotChat/client.lua
The code now properly checks if the response exists before trying to access its properties. This prevents potential errors when the API response is null, which could happen during network failures or timeouts.
Closes #1037
=> fix: add null check for API response

lua/CopilotChat/utils.lua
This change adds filetype detection for .h header files to be recognized as C language files, improving syntax highlighting and language-specific features for C header files in the CopilotChat plugin.
Signed-off-by: Tomas Slusny <slusnucky@gmail.com>
Closes #1043
=> feat: detect .h files as c filetype

lua/CopilotChat/utils.lua
Replace manual binary extension filtering with proper filetype detection using plenary.filetype library. This improves file type identification and eliminates the need to maintain a large list of binary extensions.
The change simplifies the codebase while providing more accurate results when determining which files to include in scanning operations.
=> refactor: use plenary.filetype for file type detection

test/plugin_spec.lua
Add missing mock for the plenary.filetype module in the test suite to ensure tests can run properly without the actual dependency.
=> test: add mock for plenary.filetype module

lua/CopilotChat/init.lua
When saving chat history, include current prompt in the history array. This ensures that unsent (in-progress) prompts are also preserved when saving the chat history to a file.
Closes #1049
=> fix: properly save prompt in history

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/init.lua
Update model selection logic to use model names with versioning instead of just IDs. This improves user experience by showing more descriptive model names in the selection UI and ensures the latest version of each model is preferred when filtering available models.
Also updates the default model to the latest gpt-4o-2024-11-20 version.
Related https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/1052#issuecomment-2751530966
=> feat: use model name and versioning for model selection and switch to gpt-4o-2024-11-20

lua/CopilotChat/config/providers.lua
These models do not actually work but have same name as non-paygo version (o3-mini)
Closes #1058
=> fix: filter out paygo models from Copilot Chat

lua/CopilotChat/utils.lua
Closes https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/1071
I found this when trying to add a #files context, and I only have ripgrep 13.x installed on my system.
=> fix: use --max-depth arg name for ripgrep <14 compat

README.md, doc/CopilotChat.txt, lua/CopilotChat/config.lua, lua/CopilotChat/ui/chat.lua
This resolves #1080.
Example:
```lua
window = {
layout = function()
if vim.o.columns > 2 * vim.o.lines then
return 'vertical'
else
return 'horizontal'
end
end
},
```
=> feat: accept a function that returns the layout to use

lua/CopilotChat/client.lua
The response_text variable was being captured before the response body was parsed. This commit ensures that response_text is updated after parsing is complete, which provides the correct final text for processing.
Closes #1064
=> fix(client): update response_text after parsing response

lua/CopilotChat/config/providers.lua
Before the code was assuming that context window = input tokens, but its total. Also some models arent reporting the input and output correctly, so use default when result is 0
=> fix: handle invalid context window size in GitHub models

lua/CopilotChat/config/mappings.lua
Use utils.filename() to normalize the filename value in the diff object, ensuring consistent path handling.
=> fix(diff): normalize filename

lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Adds a new configuration option `include_contexts_in_prompt` that allows users to control whether context descriptions should be included when building the prompt for Copilot Chat. This is useful for cases where users want to reduce prompt size or customize how context information is presented to the AI.
The option defaults to true to maintain backward compatibility.
=> feat: add option to disable contexts in prompts

lua/CopilotChat/utils.lua
closes #1091 
As I have explained, the current implementation of `utils.buf_valid` is not excluding `terminal buffer`, that is causing the token exceed problem.
Added a condition to check if the buffer is `terminal_buffer` using `buftype`.
```lua
--- Check if a buffer is valid
--- Check if the buffer is not a terminal
---@param bufnr number? The buffer number
---@return boolean
function M.buf_valid(bufnr)
return bufnr
and vim.api.nvim_buf_is_valid(bufnr)
and vim.api.nvim_buf_is_loaded(bufnr)
and vim.bo[bufnr].buftype ~= 'terminal'
or false
end
```
=> fix(validation): Ensure If the `terminal buffer` is excluded.

README.md, doc/CopilotChat.txt, lua/CopilotChat/config.lua
=> feat: update default model to gpt-4.1

lua/CopilotChat/config/mappings.lua
Use filepath for the full path when accepting a change.
Fixes #1153
=> fix: #1153 use filepath on accept

lua/CopilotChat/utils.lua
=> Properly null check opts.glob when rigpgrep is not available

Makefile, README.md, lua/CopilotChat/tiktoken.lua
- add windows support in Makefile
- dynamically load `tiktoken_core` lib
**tiktoken_core** works without any shenanigans.
```lua
return {
"CopilotC-Nvim/CopilotChat.nvim",
build = "make tiktoken",
}
```
=> feat: add Windows_NT support in Makefile and dynamic library loading

lua/CopilotChat/config/prompts.lua
Changes the commit prompt's sticky reference from '#git:staged' to '#gitdiff:staged' to properly match the expected format for retrieving staged changes when generating commit messages.
=> fix: update sticky reference for commit messages

lua/CopilotChat/functions.lua
Previous check for empty schema broke this, the check should be done only after input type is checked
=> fix: check for explicit uri input properly

lua/CopilotChat/config/functions.lua, lua/CopilotChat/utils.lua
To improve accuracy, use vim.filetype.match instead of plenary filetype when not filtering lists of files.
Closes #1181
=> fix(functions): use vim.filetype.match for non bulk file reads

lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
message can be triggered from other places other than chat so just show chat overlay instead
=> fix(chat): show messages in overlay

lua/CopilotChat/init.lua
Move the check for empty prompt and resolved tools before making the ask call. This ensures that unnecessary user messages are removed and the finish callback is called early, preventing redundant processing. Also remove assistant message if all tool calls are handled.
=> fix(chat): handle empty prompt and tools before ask

lua/CopilotChat/init.lua
Previously, unhandled tool calls were simply removed from the assistant message, which could lead to confusion or lack of feedback. Now, when a tool call is skipped, an explicit error result is added to the resolved tools, indicating that the user skipped the function call. This improves transparency and makes the handling of skipped tool calls clearer.
=> fix(chat): handle skipped tool calls with explicit error result

lua/CopilotChat/init.lua
Adds a call to vim.api.nvim_exec_autocmds for the 'User' event with the 'CopilotChatLoaded' pattern at the end of the setup function. This allows external plugins or user configs to react when CopilotChat has finished loading. Also removes unused highlights_loaded state assignment.
=> feat(setup): trigger CopilotChatLoaded user autocommand

lua/CopilotChat/client.lua, lua/CopilotChat/utils.lua
Refactored provider handling in Client to use OrderedMap, improving consistency and sorting. Added generic type annotations for OrderedMap and introduced a get_cached helper for cache management. This change simplifies provider filtering and caching logic for models and info.
=> refactor(client): use OrderedMap for provider management

README.md, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/ui/chat.lua
Refactored chat window API to use `get_message(role, cursor)` and `get_block(role, cursor)` for both last and cursor-closest access. Removed legacy `get_closest_message` and `get_closest_block` methods. Updated mappings and documentation to reflect unified API. This simplifies usage and improves consistency for message/block retrieval and removal actions.
=> refactor(chat): unify message/block API for cursor access

lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
Adds support for displaying the assistant's reasoning above messages in the chat UI as virtual text. Reasoning is now streamed and stored separately from content, and models with reasoning capability are indicated in the model selector. This improves transparency of model responses and debugging.
=> feat(ui): show assistant reasoning as virtual text

lua/CopilotChat/ui/chat.lua
Refactored Chat:get_block to properly select the closest block to the cursor, considering the role filter and ensuring correct fallback to the last matching block. This improves accuracy when interacting with chat blocks in the UI.
=> fix(chat): correct block selection logic by cursor

lua/CopilotChat/client.lua, lua/CopilotChat/completion.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/constants.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
Move role strings and plugin name to a dedicated constants module. Refactor all usages to reference the new constants. This improves maintainability and reduces duplication across the codebase.
=> refactor(constants): centralize role and plugin name constants

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/init.lua
Refactor prompt configuration to allow template substitution in system_prompt strings using curly braces (e.g. {COPILOT_BASE}). This enables more flexible and composable prompt definitions. Also update callback signature to use the full response object. Update README to reflect new prompt usage.
BREAKING CHANGE: callback receives the full response object instead of just content.
=> refactor(prompts)!: support template substitution in system_prompt

lua/CopilotChat/config.lua, lua/CopilotChat/config/prompts.lua
Update the type annotation for system_prompt to allow nil and fix its initialization to use the shared prompt. Also, update the callback in prompts.lua to use response.content for line parsing, ensuring correct diagnostics extraction.
=> fix(config): correct system_prompt type and callback usage

README.md, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/init.lua
Remove recursive prompt expansion and placeholder substitution for system prompts. Now, system prompts reference other prompts by name directly, and the base instructions are appended automatically. This improves clarity and maintainability of prompt configuration.
=> refactor(prompt): simplify system prompt resolution logic

lua/CopilotChat/completion.lua
Previously, input completion was triggered for tools without a defined `uri`, which could lead to errors or unexpected behavior. This change ensures that input completion only occurs when both the tool and its schema are present and the tool has a valid `uri` property.
=> fix(completion): require tool uri for input completion

Makefile, scripts/test.lua
Previously, the Makefile required a command to run tests after loading the test script. Now, the test script itself runs the tests automatically, simplifying the Makefile and ensuring consistent test execution.
=> fix(test): run tests automatically in test script

tests/functions_spec.lua, tests/init_spec.lua
Add comprehensive unit tests for CopilotChat.functions covering uri_to_url, match_uri, parse_schema, and parse_input. This improves test coverage and ensures correct behavior for URI parsing and schema handling.
=> test(functions): add unit tests for functions module

lua/CopilotChat/utils.lua, tests/utils_spec.lua
Replace custom glob pattern conversion and scandir fallback with native vim.lpeg and vim.uv.fs_scandir for file matching. This simplifies code, removes redundant logic, and improves compatibility. Also remove related unit tests for glob_to_pattern.
Closes #1331
Closes #1332
=> refactor(utils): remove custom glob to pattern logic

Makefile
=> fix(makefile): handle MSYS_NT as a valid Windows environment

lua/CopilotChat/config/prompts.lua
Replaces the 'sticky' property with 'resources' in the Commit prompt configuration to improve clarity and maintain consistency with other prompt definitions.
=> refactor(prompts): use resources instead of sticky for Commit

lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
=> Fix #1352 : configuration parameter to stop on tool failure

lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Renames `stop_on_tool_failure` to `stop_on_function_failure` in config and related code for improved clarity and consistency. Updates type annotations and usage to reflect the new naming. No functional changes.
=> refactor(config): rename tool failure option for clarity

lua/CopilotChat/config/functions.lua
Adds a new scope to the diagnostics function where the user specifies that only diagnostics found inside the visual selection are to be included in the prompt's context.
This implements #1350
=> feat(functions): add scope=selection to diagnostics

lua/CopilotChat/config/prompts.lua
Extend Commit prompt to handle buffer replacement when COMMIT_EDITMSG is opened. This allows generating commit messages that can fully replace the buffer, improving workflow for staged changes.
=> feat(prompts): support buffer replacement in commit messages

lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/init.lua, lua/CopilotChat/resources.lua, lua/CopilotChat/select.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/utils.lua, lua/CopilotChat/utils/curl.lua
Move all curl-related logic from utils.lua to a new utils/curl.lua module. Update all internal references to use the new module. Mark old curl functions in utils.lua as deprecated. This improves code organization and makes curl logic easier to maintain and extend.
=> refactor(utils): split curl logic into separate module

lua/CopilotChat/ui/chat.lua, lua/CopilotChat/utils/files.lua
Refactor file and grep picker utilities to use the working directory (cwd) instead of passing the path as a command argument. This improves the picker display.
Also, update chat auto-fold logic to only close folds if a fold exists at the target line, preventing unnecessary foldclose calls.
Closes #1108
=> feat(functions): use cwd for file and grep commands

lua/CopilotChat/init.lua
Removes unnecessary BLOCK_OUTPUT_FORMAT usage for tool error and data outputs. Tool results are now returned as plain strings, improving readability and reducing formatting complexity. Also removes unused files module import.
=> refactor(core): simplify tool output formatting

lua/CopilotChat/config/prompts.lua, lua/CopilotChat/utils/files.lua
Update code block examples in prompts to use absolute file paths with {DIR} prefix. Refactor filename comparison to use vim.fs.normalize for consistency and reliability.
Closes #1377
=> fix(files): generate absolute paths in code blocks

lua/CopilotChat/client.lua, lua/CopilotChat/tiktoken.lua
Use more accurate token prediction when tiktoken core is not available
=> feat(tiktoken): improve token counting accuracy

lua/CopilotChat/ui/chat.lua
The previous implementation used `vim.fn.strwidth()` to calculate the end column for header highlighting. This function returns the display width, which can differ from the byte length when multi-byte characters like emojis are present.
Since the `end_col` for extmarks expects a byte-based index, this caused the highlighting to be applied incorrectly.
This patch corrects the issue by using the byte length (`#header_value`) for the `end_col` of the highlight extmark, while still using `vim.fn.strwidth()` for `virt_text_win_col` to ensure correct visual alignment of UI elements.
Fixes #1384
=> fix: Correct header highlighting for multi-byte characters

lua/CopilotChat/config/providers.lua, lua/CopilotChat/ui/chat.lua, lua/CopilotChat/utils/files.lua
- Remove redundant directory creation and scheduling from file write
- Ensure token file directory is created only when saving token
- Refactor GitHub device flow polling to use recursion instead of loop
- Add logging for token save location
- Restore chat overlay when message is empty
- Clear status and message notifications after authorization
Closes #1388
=> fix(auth): improve token saving and polling logic

lua/CopilotChat/utils/diff.lua
Replace vim.notify with plenary.log.debug in diff apply function to avoid user-facing warnings and improve logging granularity. This change helps keep the UI clean while still providing debug information for failed diff applications.
=> refactor(diff): use plenary.log for debug logging

lua/CopilotChat/config/mappings.lua, lua/CopilotChat/utils/diff.lua, tests/diff_spec.lua
Refactored diff preview logic to process all code blocks for a file in one pass, improving consistency and correctness. Updated diff utility functions to accept lines instead of buffer numbers, and adjusted context lengths for more accurate region detection.
=> feat(diff): apply all code blocks for a file at once when showing diff

lua/CopilotChat/client.lua, lua/CopilotChat/health.lua, lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua
Refactored plugin initialization to use lazy loading via metatable, setting an `initialized` flag and moving setup logic to `init()`. Replaced `add_providers` with `set_providers` for clarity. Improved health check to verify initialization. Cleaned up chat state handling and logging logic for better reliability and maintainability.
=> perf(core): do not require calling setup(), add lazy initialization

lua/CopilotChat/ui/chat.lua
Move message parsing to get_messages, removing redundant parse calls from get_block, get_message, add_message, and remove_message. This simplifies the code and ensures messages are always parsed when retrieved, reducing unnecessary parsing and improving performance.
=> refactor(chat): streamline message parsing logic

lua/CopilotChat/config/providers.lua
Wrap curl.post in pcall to prevent errors when enabling model policy. This avoids potential crashes if the request fails.
=> fix(provider): safely call curl.post for model policy

lua/CopilotChat/config.lua
Remove redundant markdown-style prefixes from chat headers in config. This makes the headers cleaner and easier to customize.
=> refactor(config): simplify chat headers formatting

lua/CopilotChat/init.lua
Simplifies plugin initialization by merging the init logic into the setup function. Removes the separate init function and ensures all configuration, provider setup, and chat initialization are handled in setup. This reduces redundancy and makes the initialization flow clearer.
=> refactor(init): merge init logic into setup for simplicity

lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
this breaks notification listeners
=> fix(chat): do not create multiple chat isntances

lua/CopilotChat/config/mappings.lua, lua/CopilotChat/init.lua
functions call get_messages and those use vim.api functions. So move it at start of show_info block
=> fix(mappings): make sure function resolution is not ran in fast context

README.md, lua/CopilotChat/config/functions.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/functions.lua
- Replace separate `buffer`, `buffers`, `selection`, `diagnostics` and 'quickfix' resources with a unified `buffer` and `selection` resource that automatically includes diagnostics in the output.
- Replace `register` resource with simplified `clipboard` resource
- Add new `bash` and `edit` tools for LLM-only usage.
- Update README to reflect new resource/tool types and usage.
- Remove unused/duplicated mappings and code for old resources.
- Improve enum handling and selection UI for resource schemas.
BREAKING CHANGE: Removes `buffers`, `diagnostics`, `register`, and `quickfix` resources. Use `buffer`, `selection`, or `clipboard` instead.
=> refactor(functions)!: unify buffer/selection/diagnostics resources

lua/CopilotChat/config/mappings.lua
When displaying resource previews, prefer showing the resource name instead of the URI if the name is available. This improves readability in the preview header, especially for resources with user-friendly names.
=> fix(mappings): use resource name if available in preview header
