README.md, cspell-tool.txt, cspell.json, init.lua, rplugin/python3/plugin.py
- Add usage with lazy.nvim
- Add todo for init.lua
[![install with lazy](https://i.gyazo.com/42bd67129bae15a5c9224ddb552bd605.gif)](https://gyazo.com/42bd67129bae15a5c9224ddb552bd605)
=> Add usage with lazy.nvim

lua/CopilotChat/init.lua
This is needed so syntax highlighting for stuff like code blocks or lists do not breaks when copilot replies those right away
=> Add newline before CopilotChat: if first token is not alphanumeric

MIGRATION.md, README.md
Did not updated rest of the README yet but at least for migration this should be enough.
=> Add migration guide to README.md

MIGRATION.md, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
- Add show_system_prompt option
- Add show_user_selection option
- Add show_folds option
=> Add support for folds to canary

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/prompts.lua
Now submit_code and submit_prompt properly try to find first match from the end so you dont need to cursor over specific blocks. This is also prerequisite for showing current diff as float or in corner somewhere.
=> feat(CopilotChat): Improve line separation and prompt update logic, add diff view

MIGRATION.md, README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/debuginfo.lua, lua/CopilotChat/init.lua, lua/CopilotChat/prompts.lua, lua/CopilotChat/select.lua, lua/CopilotChat/spinner.lua, lua/CopilotChat/utils.lua
- Improve documentation and examples in README.md and add info about new features
- Add luadoc strings to most types and also to configuration
- mappings.complete changed to mappings.complete_after_slash to be more clear
- remove rtpath report from debuginfo
=> feat: Improve CopilotChat documentation and configuration

MIGRATION.md, lua/CopilotChat/health.lua
This addresses another issue from MIGRATION.md todo list
- Add curl, and git health checks
- Add dependency health checks
- Add warning for non-nightly neovim as that disables some features
=> feat: Add new healthchecks

README.md, lua/CopilotChat/code_actions.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/select.lua
This allows updating selection without having to call chat.ask or chat.open again
=> feat: Rework how selectors work so only last buffer is remembered

README.md
It was part of ChatInPlace note but that one isnt there anymore and badge is nicer
=> Add back Discord info

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/diff.lua, lua/CopilotChat/init.lua, lua/CopilotChat/prompts.lua, lua/CopilotChat/spinner.lua
https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/5115805/9dee5e54-b3b7-4214-a142-dec1a3985f53
- Instead of using tooltip just replace the chat window
- Highlight both syntax + diff
- Instead of replacing colors, blend foreground diff colors as background colors
- Optimize existing prompts to generate better diffs
=> feat: Improve diff display and optimize existing prompts for diffs

lua/CopilotChat/chat.lua, lua/CopilotChat/diff.lua, lua/CopilotChat/init.lua
This should hopefully solve issue with plugin being loaded on buf read
=> fix: Delay creation of chat and diff buffers until they are needed

lua/CopilotChat/chat.lua
Stable do not supports float footer so just skip it.
=> fix: Check if we are on nightly when setting chat footer

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
Instead of just erroring and not handling the errors handle and show them properly.
=> fix: Gracefully handle errors from copilot

lua/CopilotChat/context.lua
Bug on line 83.
As was, it always returned bool, nil, which would push into the next conditional, which could fall through if the file type is not directly recognized.
In these cases, it's also returning nil. Calling functions treat the response as a table, which leads to unexpected failures.
=> Fix broken context extraction for large files.

lua/CopilotChat/chat.lua, lua/CopilotChat/diff.lua, lua/CopilotChat/init.lua, lua/CopilotChat/spinner.lua
=> feat: Switch from virt text to virt lines for help

lua/CopilotChat/chat.lua, lua/CopilotChat/debuginfo.lua
It is not working properly with virt_lines due to
https://github.com/neovim/neovim/issues/27887
=> fix: Remove concealcursor configuration

README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
=> feat: Save and load chat history

lua/CopilotChat/chat.lua, lua/CopilotChat/overlay.lua
Just small cleanup to use inheritance properly
=> Use method overriding for defining buf_create logic for overlays

MIGRATION.md, README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
=> feat: Add back option to hide help

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
=> 194 add callback response

README.md, lua/CopilotChat/config.lua
Split configuration to section with newlines
Group similar configs together in sections
=> docs: Make configuration easier to navigate through

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
=> 203 add custom mappings

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
=> feat: Add option to auto enter insert mode

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
=> feat: Add insert mode mappings as well

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua
=> fix: Properly start insert mode on opening window, regardless of source

MIGRATION.md, README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Example of python version format config:
```
{
question_header = '## User ',
answer_header = '## Copilot ',
error_header = '## Error ',
}
```
Closes #233
=> feat: Make question/answer/error headers configurable

lua/CopilotChat/utils.lua
It looks really bad with numbers enabled
=> feat: Do not push help and tokens to left column

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
Refer https://github.com/CopilotC-Nvim/CopilotChat.nvim/discussions/234
=> Feature: Add Action to Yank Response to Register

lua/CopilotChat/health.lua
Also do not warn on stable anymore, we should be fully supporting it now.
=> feat: Add check for supported nightly versions of neovim

lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Properly check if window layout config changed before resetting (closing/reopening) whole window.
=> fix: Properly check if window layout changed before resetting

lua/CopilotChat/select.lua
This allows accepting diffs for empty buffers or inserting new code
Closes #259
=> feat: Allow empty lines to be used as selection as well

lua/CopilotChat/copilot.lua
Prevents freezes on very slow connections
Closes #262
=> fix: Authenticate asynchronously instead of blocking the editor

lua/CopilotChat/context.lua
Uses same logic as @buffer used for smaller files. This also reduces the small file threshold, 1k lines was probs a bit too much.
=> feat: Send whole content of small files in @buffers as well

lua/CopilotChat/copilot.lua
=> fix: Check if github token file is readable and exists

lua/CopilotChat/copilot.lua
Looks like some of the current ones werent exactly correct (like
machineid). Also do not lie in user agent and editor plugin headers.
=> fix: Use latest vscode copilot headers

lua/CopilotChat/prompts.lua
Retrieved from latest vscode copilot chat plugin using mitmproxy
Closes #271
=> feat: Update Copilot prompts to same one as vs code uses

README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua
Did not had perms to push to the other PR so making new one
Fixes #279
=> feat: allow height and width for horizontal and vertical

lua/CopilotChat/chat.lua
=> feat: Remove confusing double wrapping from chat

lua/CopilotChat/init.lua
Plugin should chcek if buffer actually exists when chatting about it
=> fix: Check if buffer is valid before getting filetype + filename

README.md, lua/CopilotChat/init.lua
See https://github.com/CopilotC-Nvim/CopilotChat.nvim/discussions/307
=> feat: Add method and command to stop current copilot output

lua/CopilotChat/copilot.lua
=> fix: Load token from both apps.json and hosts.json

lua/CopilotChat/integrations/telescope.lua
=> fix(telescope): ensure correct selection with telescope prompt actions

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua
CC @deathbeam & CC @jellydn 
I haven't touched Lua in a while and don't really know how the codebase works anymore. Could you guys check if I did anything wrong
Tentatively closes #366
=> Allow runtime selection of models with `:CopilotChatModels`

README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua
Also update documentation for default accept binding and general small cleanup.
Closes #359
Closes #350
Closes #357
Closes #309
=> fix: Handle layout replace closing, handle empty embed results

README.md
For Arch Linux user, we can install it from aur!
=> Add `tiktoken_core` installation method

README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/integrations/fzflua.lua, lua/CopilotChat/integrations/telescope.lua, lua/CopilotChat/utils.lua
- Cleanup auto insert behaviour and move it to chat.lua
- Add support for moving cursor to end of buffer before entering insert mode in the chat buffer
- Cleanup configuration (move yank register config near the mapping)
Closes #379
=> Cleanup auto insert behaviour and add support for insert at end

lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
=> Move help to separate window

.all-contributorsrc, README.md, lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua
=> fix: Properly load auto follow cursor config when appending text

lua/CopilotChat/init.lua
If you dont select anything and just ESC it sets the model to nil atm.
=> Null-check model choice after :CopilotChatModel

lua/CopilotChat/copilot.lua
=> Add O1 support

lua/CopilotChat/copilot.lua
This prevents issue where claude request takes longer than auth and breaks on first ask.
=> Only ask questions after claude request completes

lua/CopilotChat/select.lua
=> fix: Ensure that start_col and end_col selection is awlays within bounds

README.md
Encourage the user to check that "Copilot chat in the IDE" is enabled.
=> Added Post-Installation to README.md

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua
- Dynamically resolve max token count
- Dynamically resolve tokenizers
- Use only stream function not both callback and stream and distinguish type of response instead
=> Grab model data dynamically instead of hardcoded

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/tiktoken.lua
- Deduplicate models based on version
- Sort models by name
- Use shortest model id based on version in ouput
=> Improve model listing and add info about :CopilotChatModels to config

lua/CopilotChat/copilot.lua, lua/CopilotChat/prompts.lua
With new available models this is probably not needed anymore and everyone can probably live with some hallucinations here and there when asking the AI about its model.
Closes #453
=> Remove GPT-4 forcing from system prompt

lua/CopilotChat/tiktoken.lua
- Instead of using async, just use curl callback
- schedule_wrap the inner function for thread safety
=> Improve tiktoken download paralellization

lua/CopilotChat/copilot.lua
Removes all non-standard characters to avoid issues with copilot API (especially claude).
Closes #464
=> Automatically sanitize input sent to copilot API

lua/CopilotChat/copilot.lua
Reverts CopilotC-Nvim/CopilotChat.nvim#467
Closes #469 
Opens #464
=> Revert "Automatically sanitize input sent to copilot API"

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/utils.lua
This greatly improves readability and makes the code less error prone
=> Use plenary.async instead of callback hell

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua
=> Add config for setting log level

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
Generate unique ID for every job run and reset/change it when new job is started or when job is stopped.
=> Improve job cancellation

lua/CopilotChat/copilot.lua
This is to match what VSCode is doing
=> Add max_tokens to chat requests

lua/CopilotChat/init.lua
=> Improve help display

lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/prompts.lua
=> Automatically clear copilot diagnostics on asking new question

lua/CopilotChat/init.lua
=> Add separators when showing diff/prompt/selection windows

lua/CopilotChat/copilot.lua, lua/CopilotChat/overlay.lua, lua/CopilotChat/spinner.lua
This prevents initial hiccup when opening first window of a chat session
=> Load github token asynchronously

lua/CopilotChat/init.lua
This change allows selecting different diffs by simply navigating cursor to the diff codeblock.
Potentionally closes #318
=> Increase flexibility of diff selectors

README.md, lua/CopilotChat/chat.lua
And add render-markdown integration info
=> Automatically register copilot-chat for treesitter markdown

lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua
=> Add agent descriptions to autocomplete

README.md, lua/CopilotChat/config.lua
=> Include filenames in buffer context selection, improve buffers context

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua
Add caching mechanism for embeddings to avoid re-computing them for the same content. This improves performance by storing and reusing previously computed embeddings based on filename and content hash.
=> perf: add caching for embeddings

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua
Introduce raw filetype for somethign that should just be embedded directly (like prompts).
=> Standardize context embedding format

lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/overlay.lua, lua/CopilotChat/spinner.lua, lua/CopilotChat/utils.lua
Introduce utils.buf_valid helper to streamline buffer validation across the plugin. Extract apply_diff function to remove code duplication and improve consistency of diff application. This change makes the code more maintainable and reduces potential errors in buffer handling.
=> refactor: improve buffer validation and diff handling

lua/CopilotChat/select.lua
The change removes the need to track columns in visual line selection and uses line-based selection instead. This simplification maintains the same functionality while making the code more maintainable and less error-prone.
=> refactor(select): simplify visual line selection

lua/CopilotChat/context.lua
Added proper validity checks for file and buffer functions to prevent errors when accessing non-existent files or invalid buffers. This makes the error handling more robust and prevents potential crashes.
=> fix: add validity checks for file and buffer functions

lua/CopilotChat/select.lua
I was wondering why my Copilot Chat wasn't picking up the error messages during /fix commands, and I think that's why :)
Keep up the good work!
=> fix(select): ensure diagnostics are passed to the model when in "Visual"

lua/CopilotChat/copilot.lua
After refactor to plenary.async we accidentally lost a way to make stream and callbacks work the same. So split parsing logic to parse_line function and use it on final response as well when the response is non-streaming
=> fix: fix o1-preview non-streaming response parsing

lua/CopilotChat/init.lua
The selection handling logic has been reorganized to be more robust and maintainable:
- Moved highlight_selection from public to local function
- Added update_selection function to handle source buffer tracking
- Fixed selection updates when switching between windows
- Selection state is now updated based on previous window
- Removed redundant selection updates from open function
- Fixed buffer reference in BufEnter/BufLeave autocmds
=> refactor: improve selection handling and highlighting

lua/CopilotChat/init.lua
Refactor selection state management to use getter function instead of storing selection in global state. This improves code maintainability by:
- Removing mutable selection state from global state object
- Adding type-safe get_selection() function to encapsulate selection logic
- Ensuring selection is always retrieved from current source
- Moving selection logic closer to where it's used
The change also fixes a bug where header info was not properly validated before being used as source of truth in get_diff().
=> refactor: cleanup selection state management

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/prompts.lua
Streamline the way diagnostics are handled in prompts by:
- Move diagnostics check from general prompt into explain prompt
- Split explain prompt into multiple lines for better readability
- Update documentation and config to reflect these changes
This creates a more focused approach where diagnostics are examined as part of code explanation rather than being a separate concern.
=> refactor(prompts): improve diagnostics handling system

lua/CopilotChat/copilot.lua
Add detailed trace logging using vim.inspect for models and agents data structures to help with debugging and development.
=> feat: add trace logging for models and agents

lua/CopilotChat/chat.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
Reimplements chat section parsing to better handle code blocks, headers and
sections by storing them in a structured way within the Chat class. This
enables more reliable navigation between sections, code blocks and diffs.
Key changes:
- Add sections and blocks tracking in Chat class
- Improve code block and header parsing reliability
- Consolidate duplicate header parsing code
- Add get_closest_section and get_closest_block helper methods
- Refactor diff handling to use new block parsing
- Clean up quickfix list generation using new block data structure
=> refactor: improve chat output parsing and selection handling

lua/CopilotChat/chat.lua, lua/CopilotChat/diff.lua, lua/CopilotChat/overlay.lua, lua/CopilotChat/utils.lua
Add extendable constructor and move overlay create logic to :create
=> refactor: improve class extending system

lua/CopilotChat/init.lua
=> refactor: use cwd from dir changed event

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua, lua/CopilotChat/ui/debug.lua, lua/CopilotChat/ui/diff.lua, lua/CopilotChat/ui/overlay.lua, lua/CopilotChat/ui/spinner.lua, lua/CopilotChat/utils.lua
- Add proper type annotations and documentation for all classes and methods
- Reorganize UI components into separate ui/ directory
- Remove redundant type comments in favor of proper annotations
- Improve class hierarchy and inheritance relationships
- Clean up function signatures and return types
- Fix overlay component argument order consistency
=> refactor(types): improve type safety and organization

lua/CopilotChat/init.lua
Pass chat configuration to functions that were previously using global state config, making the code more reliable and avoiding potential race conditions when multiple chat instances are running simultaneously.
=> fix(selection): properly pass chat config to functions

README.md, lua/CopilotChat/config.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
- Moved UI-related config fields to shared section
- Updated type definitions and documentation
- Fixed selection highlight to respect config
- Improved token count display formatting
=> refactor(config): reorganize shared/static config fields

lua/CopilotChat/context.lua
Simplify context filtering and ranking by removing redundant data structures and utilizing more of vim's built-in table functions. This change:
- Removes OrderedMap usage in favor of direct table operations
- Combines mapping and scoring operations
- Preserves original content in outline objects
- Uses vim.tbl_map and vim.tbl_extend for cleaner data transformations
- Improves code readability and reduces complexity
The functionality remains the same while making the code more maintainable.
=> refactor: simplify context filtering and ranking

lua/CopilotChat/init.lua
Replace direct mapping key access with named mapping lookups to improve code organization. Add descriptive labels to keymaps using the plugin name and mapping name. This change makes the key mapping system more maintainable and provides better documentation in the key binding help.
=> refactor(mappings): improve key mapping API and descriptions

.luarc.json, lua/CopilotChat/context.lua, lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/utils.lua
The changes make various file operations and context resolution properly async by:
- Converting synchronous UV calls to async versions
- Moving context resolution inside async block
- Making tiktoken data loading fully async
- Converting directory scanning to async version
- Adding proper error handling for async UV operations
This improves overall responsiveness of the plugin by preventing blocking operations from freezing the editor.
=> fix: make file operations and contexts async

lua/CopilotChat/init.lua
Replace manual buffer search and creation logic with built-in Neovim functions bufadd() and bufload(). This change makes the code more concise and reliable by leveraging Neovim's native buffer management APIs.
The new implementation:
- Removes redundant buffer search loop
- Uses bufadd() to add new buffer
- Uses bufload() to ensure buffer is loaded
=> refactor: simplify buffer handling using builtin functions

README.md
Improve readability of requirements section by:
- Renaming "Prerequisites" to "Requirements"
- Consolidating required and optional dependencies into a cleaner list format
- Making the documentation more concise while preserving all information
- Adding links to package manager sections
=> docs(readme): reorganize requirements section

lua/CopilotChat/copilot.lua
Previously, the content truncation was based on line count which could lead to inconsistent token usage when lines had varying lengths. This change switches to character-based truncation to provide more predictable token consumption.
Key changes:
- Introduced LINE_CHARACTERS constant (100 chars per line)
- Updated BIG_FILE_THRESHOLD and BIG_EMBED_THRESHOLD to use char count
- Refactored generate_line_numbers into generate_content_block that handles both line numbering and truncation
- Made truncation logic count total characters instead of lines
=> refactor: switch to character-based truncation

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/notify.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/ui/spinner.lua
Add a new notification system to provide user feedback for background operations like file scanning, model fetching, and API calls. This improves the user experience by making it clear when the plugin is performing work.
The changes include:
- New notify module for pub/sub event system
- Integration with spinner UI to show status messages
- Status notifications for file operations, API calls, and embeddings
- Removed redundant logging in favor of user-visible notifications
- 
https://github.com/user-attachments/assets/83c1bf99-1258-434e-9f73-4a9b667f6650
=> feat: add status notifications for background tasks

lua/CopilotChat/init.lua
Change resolve_prompts to handle entire config object instead of just system_prompt. This allows prompts to modify any config values, not just the system prompt, making the prompt resolution system more flexible.
The change maintains backwards compatibility while enabling more advanced prompt configurations.
=> refactor(prompt): improve config handling in resolve_prompts

lua/CopilotChat/context.lua, lua/CopilotChat/copilot.lua, lua/CopilotChat/ui/debug.lua
Improve memory usage and performance by:
- Replace original field with outline in context struct
- Increase TOP_SYMBOLS limit from 64 to 100
- Optimize content block generation to avoid unnecessary string operations
- Simplify embedding messages generation by removing file grouping
- Use outline content when available for more efficient context handling
=> refactor: optimize context handling and content blocks

lua/CopilotChat/copilot.lua
Older curl versions do not support it
Closes #677
=> Remove fail with body curl args

lua/CopilotChat/copilot.lua
Hi there! First, thank you for writing this plugin. I'm using it well. 
But I found that the o1 model returns nothing, with an empty response error message. So I fixed it. Could you please review this PR and consider merging it? I haven't contributed much before, so I apologize in advance if I've made any mistakes. Thank you!
=> fix: refactor ask function to handle content properly

README.md, doc/CopilotChat.txt
Add docs as requested in https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/720#issuecomment-2614009340
=> docs(docs): add snacks.nvim picker integration docs

lua/CopilotChat/prompts.lua
Refactor prompts to be more concise and focused while maintaining core functionality:
- Simplify copilot base instruction to focus on practical solutions
- Restructure explain prompt into clear bullet points
- Streamline code review prompt with consistent format
- Improve generate prompt with clearer block structure requirements
The changes make the prompts easier to maintain and understand while preserving all key functionality.
Closes #675
=> feat: improve prompt readability and clarity

README.md, lua/CopilotChat/client.lua, lua/CopilotChat/config.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/context.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
- Move copilot and github_models providers to separate config
- Allow specifying custom providers
Closes #723
=> feat: Refactor how providers are defined and allow custom providers

index.html
Add Prism.js language components for Vim and Lua syntax highlighting in the documentation website.
=> feat: add Vim and Lua syntax highlighting

lua/CopilotChat/client.lua
Enhance the response handling for Ollama API by:
- Adding debug logging for response lines
- Handling empty line responses
- Supporting both standard and Ollama-specific response formats
- Improving finish reason handling for stream completion
- Simplifying stream line parsing logic
The changes make the client more robust when dealing with different response formats from the Ollama API while providing better debug information.
=> fix: improve ollama response handling & error tracking

index.html
Updates the docsify configuration to include the project name and repository URL, improving documentation site navigation and identification. Also adjusts top margin for better readability.
=> docs: add project name and repository info to docsify config

lua/CopilotChat/client.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua
Move chat history handling from the client to the chat UI component to better
separate concerns and improve code organization. History is now maintained and
parsed directly in the chat UI rather than being stored in the client.
Key changes:
- Remove history field and related methods from client
- Add parse_history and load_history methods to chat UI
- Update save/load functions to work with chat UI history
- Cache section/block content during rendering for better performance
- Modifying buffer contents now allows also modifying history
=> refactor: Make history fully respect buffer contents

lua/CopilotChat/client.lua, lua/CopilotChat/context.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua, lua/CopilotChat/utils.lua
Improves symbol search algorithm by using trigram-based similarity matching instead of simple term matching. This provides better accuracy for fuzzy matches and handles compound words better.
Key changes:
- Replace basic term matching with trigram-based Jaccard similarity
- Normalize and weight symbol matches separately from filename matches
- Add reference list display in chat UI
- Move authentication status messages to more logical locations
- Fix various edge cases and improve code organization
=> refactor(search): improve symbol search and references

lua/CopilotChat/context.lua
Remove MIN_RESULTS constant and use MULTI_FILE_THRESHOLD consistently for minimum results filtering. Improve scoring by adding base score to symbol matches and simplify spatial distance calculation. Add score bonus for current file context to improve relevancy of local results.
These changes make the context selection more accurate by:
- Using consistent thresholds
- Better handling of symbol matching scores
- Prioritizing local context appropriately
=> refactor(scoring): improve context relevancy scoring

lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/init.lua
Improves agent handling in the chat client by:
- Fixing agent config extension when agent is not provided
- Correcting URL generation for agent endpoints
- Fixing agent list mapping to use proper agent IDs
- Improving type annotations for provider options
These changes make the agent-related functionality more robust and type-safe throughout the codebase.
=> fix: correct agent handling in chat client

README.md, lua/CopilotChat/client.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/utils.lua
Refactor HTTP request handling to improve JSON processing and error handling:
- Add json_request/json_response flags to automatically handle JSON conversion
- Make get_headers optional for providers
- Simplify error handling and status code checks
- Standardize header casing and content-type handling
- Remove redundant JSON encoding/decoding operations
The changes make the code more maintainable and reduce duplication while keeping the same functionality.
=> refactor(http): simplify curl request handling

lua/CopilotChat/config/providers.lua, lua/CopilotChat/tiktoken.lua
Replace multiple manual table operations with vim.iter and vim.tbl_map for better readability and more idiomatic Lua code. This change simplifies the data transformations in providers.lua and improves scheduling in tiktoken.lua.
=> refactor: improve code using vim.iter and tbl_map

lua/CopilotChat/config/prompts.lua
The changes improve explicit behavior requirements in prompt templates by:
- Adding instruction to handle line-numbered code snippets
- Expanding code review criteria to cover more quality aspects
- Clarifying exact line number requirements for code generation
- Adding more specific formatting and completeness requirements
- Improving explanation focus to cover non-obvious code aspects
The updates make the prompts more precise and help ensure more consistent and higher quality AI responses across different usage scenarios.
Closes #760
=> feat(prompts): enhance clarity of prompt instructions

README.md
Reorganize the dependencies section in README.md for better readability:
- Split dependencies into required and optional sections
- Improve formatting and layout of installation instructions
- Clean up wording and presentation of package manager options
- Add clearer note about Neovim version compatibility
=> docs: improve dependencies section organization

README.md
Add comprehensive overview section listing key features of CopilotChat.nvim including:
- Copilot Chat integration with selective context sharing
- Workspace context awareness
- Extensible provider system
- Rich chat interface
- Built-in prompts
- Context-aware responses
- Efficient token usage
=> docs: add plugin overview section to README

README.md
The README.md feature list has been enhanced with more precise and detailed descriptions of the plugin's capabilities. Key updates include:
- Clarified native Copilot Chat integration and supported models
- Added details about smart embeddings system
- Improved explanation of context sharing mechanics
- Enhanced description of the prompt system
- Refined explanations of UI and provider features
=> docs: update feature list with more detailed descriptions

README.md, lua/CopilotChat/init.lua, lua/CopilotChat/ui/spinner.lua
Add dedicated highlight group for input contexts and update existing highlight groups to better organize visual elements in the chat buffer. CopilotChatSpinner is now renamed to CopilotChatStatus for better semantics. Syntax matching is improved to handle input contexts with proper containment rules.
=> feat: improve chat buffer syntax highlighting

lua/CopilotChat/client.lua, lua/CopilotChat/context.lua
Move embedding cache functionality from client to context module to improve separation of concerns and code organization. The cache is now maintained in the context module which is more appropriate since it deals with context management.
This change simplifies the client module by removing the embedding cache responsibility while maintaining the same caching functionality in a more logical location.
=> refactor: move embedding cache to context module

lua/CopilotChat/config/prompts.lua
Refines the prompting instructions across multiple components:
- Restructured COPILOT_EXPLAIN bullet points for better clarity
- Simplified COPILOT_GENERATE instructions while maintaining functionality
- Made the prompt more concise and better organized
- Improved readability with consistent formatting
=> refactor(prompts): improve clarity of copilot prompts

lua/CopilotChat/config/providers.lua
Replace direct vim file reading and JSON decoding functions with utility functions for better error handling and code consistency. This change makes the token retrieval more robust by safely handling file reading and JSON parsing failures.
=> refactor: improve token file reading with utils

lua/CopilotChat/init.lua, lua/CopilotChat/ui/diff.lua
Added scheduler() call to ensure errors are properly handled in async contexts. Also improved buffer validation by simplifying redundant checks in diff.lua since utils.buf_valid already performs the necessary validation.
=> fix: properly handle errors in async contexts

lua/CopilotChat/utils.lua
Not available in latest neovim release yet
Closes #886
=> fix: do not use vim.fs.abspath

README.md
Update the Stargazers chart URL to include the adaptive variant parameter for better visualization on different themes and device displays.
=> feat: use adaptive variant for Stargazers chart

lua/CopilotChat/config/mappings.lua
instead of having safeguard requiring users to press jump to diff first, allow accept diff to also do this by default
=> feat: allow diff accept to jump buffers like jump_to_diff

lua/CopilotChat/config/mappings.lua, lua/CopilotChat/config/prompts.lua, lua/CopilotChat/config/providers.lua, lua/CopilotChat/init.lua, lua/CopilotChat/ui/chat.lua, lua/CopilotChat/ui/overlay.lua, lua/CopilotChat/ui/spinner.lua
This commit restructures the CopilotChat API, particularly the Chat class in ui/chat.lua. Changes include:
- Move method definitions to match class-like organization
- Add JSDoc comments for public methods
- Mark private/protected methods and properties
- Rename method 'active()' to 'focused()' for clarity
- Move class annotations from file start to declaration
- Rename 'overlay' to 'chat_overlay' to avoid property/method conflict
- Replace 'show_overlay()' method with simpler 'overlay()' name
=> refactor(api): improve Chat class organization and privacy

README.md, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/init.lua
Restructure the API documentation into logical sections for better readability and include additional API methods that were previously undocumented. Add new sections for:
- Core chat functions
- Chat window UI methods
- More comprehensive examples
This provides users with a clearer overview of the available functionality and how to use the plugin effectively.
=> docs(readme): update API reference with complete function list

lua/CopilotChat/utils.lua
- Move M.curl_args initialization to top of file with default values
- Remove unused uuid and machine_id functions
- Convert function expressions to proper function declarations
- Remove redundant DEFAULT_REQUEST_ARGS constant
- Reorder some functions for better organization
=> refactor: clean up utils module structure and function format

lua/CopilotChat/client.lua, lua/CopilotChat/context.lua, lua/CopilotChat/select.lua, lua/CopilotChat/utils.lua
on top of sending them with selection send them also with buffer context
=> feat: send diagnostics with buffer context as well

README.md, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/ui/chat.lua
New `chat.add_sticky(sticky)` method for adding sticky prompts to chat
Closes #937
=> feat: util method to add sticky prompt to chat

lua/CopilotChat/init.lua
When receiving empty responses from Copilot Chat, the code now properly handles the error case by setting an appropriate error message and displaying it to the user. This prevents silent failures and improves the user experience by providing clear feedback.
Also removes redundant condition checking and cleans up code flow for better readability.
=> fix: improve handling of empty responses

lua/CopilotChat/client.lua
Update the conversation summarization feature with:
- Rename function from `summarize_memory` to `summarize_history`
- Enhance system prompt with better formatting guidelines
- Add directive to preserve code samples and configurations
- Improve prompt clarity for better technical summaries
- Add tracking for unresolved questions/issues
These changes make history summarization more effective by producing better structured and more comprehensive technical summaries.
=> refactor: improve conversation history summarization

lua/CopilotChat/init.lua
The changes remove redundant error handling for empty responses and eliminate an unnecessary call to utils.schedule_main() in the error handling path. This simplifies the code flow while maintaining proper error reporting.
=> fix(error-handling): simplify error handling conditions

lua/CopilotChat/client.lua, lua/CopilotChat/init.lua
Enhance the context suggestion UI by:
- Adding clearer examples for context providers with descriptions
- Fixing indentation in the help text for better readability
- Adding logic to detect code blocks to prevent parsing '>' markers inside code examples as context requests
- Improving guidance for users when requesting additional context
This change makes the context help more user-friendly and prevents false positives when parsing context requests.
=> feat(context): improve context help and code block handling

lua/CopilotChat/client.lua
The formatting of the context providers help text has been improved for better readability and consistency:
- Adjusted indentation and spacing of the help text
- Made the format examples more consistently aligned
- Simplified the text structure for better clarity
- Fixed memory context handling to be more concise
=> refactor(prompt): improve context provider help text format

lua/CopilotChat/client.lua, lua/CopilotChat/init.lua, lua/CopilotChat/utils.lua
- Add StringBuffer class for efficient string concatenation by merging buffers in a balanced way based on size
- Make selection and embeddings parameters optional with proper typing
- Remove local variable shadowing in ask() function for better readability
- Move logging of response after assembling full text
- Add auto-follow in chat window after prompt
=> perf(client): optimize buffer handling for responses

lua/CopilotChat/config/contexts.lua, lua/CopilotChat/context.lua, lua/CopilotChat/utils.lua
Implement async treesitter parsing with the new ts_parse_string utility function to improve performance during context gathering. Update file processing in context providers to use vim.iter for cleaner functional approach and ensure filetype is correctly passed through the pipeline.
=> feat(context): add async treesitter parsing support

lua/CopilotChat/context.lua
Store only essential embedding data in cache and make cache keys consistent throughout the code. This change separates cache internal fields with underscore prefix and ensures clean object structure when returning cached results.
Key improvements:
- Use consistent hash key with _hash property
- Store only embedding vectors instead of full objects
- Return clean objects when retrieving from file cache
- Mark internal cache fields with underscore prefix
=> refactor(cache): improve embedding cache consistency

lua/CopilotChat/utils.lua
Add capability to filter out binary files during directory scans based on file extensions. This improves performance and helps prevent sending binary data to Copilot.
- Create comprehensive list of common binary file extensions
- Add binary_extensions field to scan options
- Implement filter_files function to centralize filtering logic
- Refactor code to use the new filtering function in all scan paths
=> feat(utils): add binary file filtering in directory scans

lua/CopilotChat/context.lua
The code was previously using MIN_SYMBOL_SIMILARITY and MIN_SEMANTIC_SIMILARITY constants, but the thresholds weren't actually being used in the ranking functions. This change removes the unused constants and simplifies the function signatures by removing the corresponding parameters.
=> refactor: remove unused similarity threshold parameters

lua/CopilotChat/utils.lua
Wrap treesitter parsing operations in vim.schedule when running in fast events to prevent potential race conditions and crashes. This ensures parser operations run in the main Neovim event loop when needed.
The fix applies to both synchronous and asynchronous parsing code paths in the ts_parse utility function.
=> fix: handle treesitter parsing in fast events

README.md, lua/CopilotChat/client.lua, lua/CopilotChat/init.lua
This feature is less useful than stream/callback output adjustment and can be replicated through it. It also causes more issues than it solves so for now just do something else.
=> refactor: remove conversation summary feature

lua/CopilotChat/tiktoken.lua
Add @async annotation to functions that load tiktoken data to better document their asynchronous behavior. This improves API documentation and helps prevent potential misuse of these functions in synchronous contexts.
=> docs(tiktoken): mark tiktoken loading functions as async

README.md, lua/CopilotChat/config.lua
this is a bit more controllable than visual || buffer + add mention in README at start
Closes #1103
=> feat: change default selection to visual only

lua/CopilotChat/init.lua
=> fix: properly validate source window when retrieving cwd

README.md
=> docs(README): Fix duplicate headers

lua/CopilotChat/init.lua
Gracefully handle errors as they come instead of manually calling show_error method and then just catch all the errors at once place
=> feat(chat): improve error handling

lua/CopilotChat/client.lua, lua/CopilotChat/config/functions.lua, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/init.lua, lua/CopilotChat/resources.lua
Simplifies resource representation by removing redundant conversion logic and standardizing resource fields. Updates resource block formatting and selection message generation to use the new structure. Cleans up unused types and improves consistency across resource-related functions.
=> refactor(resources): unify resource format and handling

lua/CopilotChat/init.lua, lua/CopilotChat/tiktoken.lua, lua/CopilotChat/ui/chat.lua
Remove unused resources import from init.lua and unnecessary variable from tiktoken.lua. Add and improve function annotations in chat.lua for better documentation and maintainability.
=> refactor: clean up annotations and unused code

README.md
=> #1283 doc update models

lua/CopilotChat/init.lua
- Use metatable for lazy config loading in main module
- Update setup to merge config values instead of replacing table
- Remove unused autocmd trigger for CopilotChatLoaded
- Set default separator directly when empty
=> refactor(core): improve config handling and setup logic

README.md, lua/CopilotChat/config/mappings.lua, lua/CopilotChat/init.lua
Separate tool resolution from function/resource resolution in core logic. This improves code clarity and maintainability by decoupling concerns.
=> refactor(core): split tool and function resolution logic

lua/CopilotChat/ui/chat.lua
As treesitter is now a requirement, it needs to be started automatically. nvim-treesitter does not auto start it anymore on latest branch so we need to do it ourselves.
=> fix(chat): automatically start treesitter if not started
